// AUTO-GENERATED — interview-English drill deck for the Opendoor pair-programming + system-design prep.
// Source: the learner's REFLEX bank (107 sentences, transcribed verbatim, en+ko) + MEMORIZE_THIS buckets,
// plus Concept/Frame/Scenario model answers authored and adversarially verified (natural senior register).
// Regenerate via /tmp/gen_iv.py rather than hand-editing. SRS-keyed with the short "iv:" prefix to stay
// well under the 120-char card_key budget; reuses the same drill/SRS engine as PATTERNS and COLLOCATIONS.

/** One survival/fluency reflex card (say the English from the Korean cue). */
export interface ReflexCard {
  key: string; // SRS card key, e.g. "iv:rfx:clarify#0"
  cue: string; // 직독직해 — Korean in English word order, " · "-chunked (production scaffold)
  meaning: string; // natural Korean meaning (for the shadow/encode mode)
  model: string; // English model to say
  core: boolean; // one of the ~18 must-be-automatic survival reflexes
}

export interface ReflexCluster {
  id: string;
  labelEn: string;
  labelKo: string;
  cards: ReflexCard[];
}

/** A concept / narration-frame / situational-scenario speaking card. */
export interface InterviewCard {
  key: string; // SRS card key, e.g. "iv:cpt:idempotency"
  group: "concept" | "frame" | "scenario";
  sub?: string; // scenarios: "interview" | "pair"
  title: string; // concept name / the frame / the situation trigger
  cue: string; // Korean prompt
  model: string; // model English answer
  note?: string;
  concepts?: string[];
}

export const REFLEX_CLUSTERS: ReflexCluster[] = [
  {
    id: "greeting",
    labelEn: "Greeting & rapport",
    labelKo: "인사 & 라포",
    cards: [
      { key: "iv:rfx:greeting#0", cue: "안녕하세요 · 정말 좋아요 · 당신을 만나서 · 감사해요 · 시간 내주셔서 · 오늘", meaning: "안녕하세요, 만나서 정말 반갑습니다. 오늘 시간 내주셔서 감사합니다.", model: "Hi, it's great to meet you. Thanks for taking the time today.", core: false },
      { key: "iv:rfx:greeting#1", cue: "저 잘 지내고 있어요 · 감사합니다 · 당신은 어때요?", meaning: "저는 잘 지내요, 감사합니다. 그쪽은 어떠세요?", model: "I'm doing well, thanks. How about you?", core: false },
      { key: "iv:rfx:greeting#2", cue: "우리 할까요? · 그냥 진행해서 · 그리고 시작할까요?", meaning: "이제 시작할까요?", model: "Should we go ahead and get started?", core: false },
      { key: "iv:rfx:greeting#3", cue: "공유할게요 · 제 화면을 · 빨리 · 보이세요? · 그게 · 괜찮게", meaning: "화면 빠르게 공유할게요. 잘 보이세요?", model: "Let me share my screen real quick. Can you see it okay?", core: false },
      { key: "iv:rfx:greeting#4", cue: "들리세요? · 제가 · 괜찮게", meaning: "제 목소리 잘 들리세요?", model: "Can you hear me okay?", core: false },
    ],
  },
  {
    id: "background",
    labelEn: "Background & self-talk",
    labelKo: "배경 & 자기소개",
    cards: [
      { key: "iv:rfx:background#0", cue: "나는 · 백엔드 엔지니어야 · 약 6년 경력의", meaning: "저는 약 6년차 백엔드 엔지니어입니다.", model: "I'm a backend engineer with about six years of experience.", core: false },
      { key: "iv:rfx:background#1", cue: "내가 골라야 한다면 · 강점 하나를 · 그건 데이터 정확성 · 숫자가 맞도록 만드는 거 · 실제와", meaning: "강점을 하나만 꼽으라면 데이터 정확성이에요 — 숫자가 실제와 맞도록 하는 일이요.", model: "If I had to pick one strength, it's data correctness — making the numbers match reality.", core: false },
      { key: "iv:rfx:background#2", cue: "내 주 스택은 · Java, C#, Oracle", meaning: "제 핵심 스택은 Java, C#, Oracle입니다.", model: "My main stack is Java, C#, and Oracle.", core: false },
      { key: "iv:rfx:background#3", cue: "나를 끌어당긴 것 · Opendoor로 · 단순해 · 그건 똑같은 문제야 · 내가 수년간 다뤄온 · 그냥 · 부동산일 뿐", meaning: "제가 Opendoor에 끌린 이유는 단순해요 — 제가 수년간 다뤄온 문제랑 똑같은데, 부동산일 뿐이에요.", model: "What drew me to Opendoor is simple — it's the same problem I've worked on for years, just with real estate.", core: false },
      { key: "iv:rfx:background#4", cue: "배우는 건 · 새 언어를 · 쉬운 쪽이야 · 나한테 · 도메인이 · 어려운 쪽 · 거기서 내가 강해", meaning: "새 언어 배우는 건 저한텐 쉬운 쪽이에요. 어려운 건 도메인인데, 거기서 제가 강합니다.", model: "Learning a new language is the easy part for me; the domain is the hard part, and that's where I'm strong.", core: false },
      { key: "iv:rfx:background#5", cue: "나 써 · AI 도구를 · Claude 같은 · 매일 · 근데 난 항상 그 사람이야 · 책임지는 · 결과에", meaning: "Claude 같은 AI 도구를 매일 쓰지만, 결과에 책임지는 건 항상 저예요.", model: "I use AI tools like Claude every day, but I'm always the one responsible for the output.", core: false },
      { key: "iv:rfx:background#6", cue: "일하고 싶어 · 어딘가에서 · 정말로 베팅하는 · AI에 · 그걸 싸우지 않고", meaning: "AI를 거부하는 게 아니라 적극적으로 받아들이는 곳에서 일하고 싶어요.", model: "I want to work somewhere that's really betting on AI, not fighting it.", core: false },
    ],
  },
  {
    id: "clarify",
    labelEn: "Clarifying & asking",
    labelKo: "명확화 & 질문",
    cards: [
      { key: "iv:rfx:clarify#0", cue: "확인할게요 · 제가 이해했는지 · 그 문제를 · 먼저", meaning: "먼저 문제를 제대로 이해했는지 확인할게요.", model: "Let me make sure I understand the problem first.", core: true },
      { key: "iv:rfx:clarify#1", cue: "줄 수 있나요? · 저한테 · 간단한 예시를 · 입력과 출력의", meaning: "입력과 출력의 간단한 예시를 하나 주실 수 있나요?", model: "Can you give me a quick example of the input and output?", core: false },
      { key: "iv:rfx:clarify#2", cue: "뭘 해야 하나요? · 입력이 비어 있으면", meaning: "입력이 비어 있으면 어떻게 처리해야 하나요?", model: "What should I do if the input is empty?", core: false },
      { key: "iv:rfx:clarify#3", cue: "있을 수 있나요? · 입력에 · 중복이 · 아니면 다 고유해요?", meaning: "입력에 중복이 있을 수 있나요, 아니면 전부 고유한가요?", model: "Can the input have duplicates, or are they all unique?", core: false },
      { key: "iv:rfx:clarify#4", cue: "얼마나 커질 수 있나요? · 입력이", meaning: "입력이 얼마나 커질 수 있나요?", model: "How large can the input get?", core: false },
      { key: "iv:rfx:clarify#5", cue: "괜찮을까요? · 가정해도 · 입력이 · 항상 유효하다고", meaning: "입력이 항상 유효하다고 가정해도 괜찮을까요?", model: "Is it okay if I assume the input is always valid?", core: false },
      { key: "iv:rfx:clarify#6", cue: "다시 말해 볼게요 · 제 말로 · 확인하려고 · 우리가 같은 이해인지", meaning: "같은 이해를 가졌는지 확인하게, 제 말로 다시 정리해 볼게요.", model: "Let me say it back in my own words to make sure we're on the same page.", core: false },
      { key: "iv:rfx:clarify#7", cue: "짧은 질문 하나 · 코딩 시작하기 전에", meaning: "코딩 시작하기 전에 짧은 질문 하나 있어요.", model: "Quick question before I start coding.", core: false },
    ],
  },
  {
    id: "approach",
    labelEn: "Stating approach & plan",
    labelKo: "접근 & 계획",
    cards: [
      { key: "iv:rfx:approach#0", cue: "여기 있어요 · 제가 어떻게 생각하는지 · 이것에 대해", meaning: "제가 이걸 어떻게 접근할지 말씀드릴게요.", model: "Here's how I'm thinking about this.", core: false },
      { key: "iv:rfx:approach#1", cue: "저 시작할게요 · 가장 단순한 버전으로 · 동작하는 · 그다음 · 만들게요 · 더 견고하게", meaning: "일단 동작하는 가장 단순한 버전부터 시작하고, 그다음 더 견고하게 만들게요.", model: "Let me start with the simplest version that works, then make it more solid.", core: true },
      { key: "iv:rfx:approach#2", cue: "먼저 · 정확하게 만들 거고 · 그다음 · 빠르게", meaning: "먼저 정확하게 만들고, 그다음에 빠르게 만들겠습니다.", model: "First I'll get it correct, then I'll make it fast.", core: false },
      { key: "iv:rfx:approach#3", cue: "저 다루겠어요 · 핵심 케이스를 · 먼저 · 그다음 · 예외 케이스를", meaning: "먼저 핵심 케이스를 처리하고, 그다음 예외 케이스를 다루겠습니다.", model: "Let me handle the main case first, then the edge cases.", core: false },
      { key: "iv:rfx:approach#4", cue: "코딩 전에 · 저 설명해드릴게요 · 제 계획을", meaning: "코딩하기 전에, 계획을 먼저 설명드릴게요.", model: "Before I code, let me walk you through the plan.", core: true },
      { key: "iv:rfx:approach#5", cue: "그 접근 · 좋게 들려요? · 너한테", meaning: "이 접근 방식이 괜찮으신가요?", model: "Does that approach sound good to you?", core: false },
    ],
  },
  {
    id: "narrate",
    labelEn: "Narrating while coding",
    labelKo: "코딩하며 말하기",
    cards: [
      { key: "iv:rfx:narrate#0", cue: "자 · 지금 제가 하는 건 · 잡는 거예요 · 기본 구조를 · 먼저", meaning: "자, 지금 제가 하는 건 먼저 기본 구조를 잡는 거예요.", model: "Okay, so what I'm doing here is setting up the basic structure first.", core: true },
      { key: "iv:rfx:narrate#1", cue: "저는 그냥 · 소리 내서 생각하는 거예요 · 그래야 · 너가 따라올 수 있게 · 제 생각을", meaning: "제 생각을 따라오실 수 있게 소리 내서 말하는 거예요.", model: "I'm just thinking out loud so you can follow my reasoning.", core: true },
      { key: "iv:rfx:narrate#2", cue: "다음으로 · 처리할게 · 핵심 케이스를", meaning: "다음으로, 핵심 케이스를 처리할게요.", model: "Next, I'm going to handle the main case.", core: false },
      { key: "iv:rfx:narrate#3", cue: "여기서 · 돌고 있어요 · 리스트를 · 찾으려고 · 일치하는 걸", meaning: "여기서는 리스트를 돌면서 일치하는 걸 찾고 있어요.", model: "Here I'm looping through the list to find the match.", core: false },
      { key: "iv:rfx:narrate#4", cue: "지금은 · 둘게 · 이 부분을 · 간단히 · 그리고 돌아올게 · 그것에", meaning: "지금은 이 부분을 간단히 두고, 나중에 다시 올게요.", model: "For now I'll keep this part simple and come back to it.", core: false },
      { key: "iv:rfx:narrate#5", cue: "지을게 · 이걸 · 명확하게 · 읽기 쉽게 · 나중에", meaning: "나중에 읽기 쉽게 이름을 명확하게 지을게요.", model: "Let me name this clearly so it's easy to read later.", core: false },
      { key: "iv:rfx:narrate#6", cue: "여기 아이디어는 · 저장하는 거예요 · 한 번 · 그리고 재사용하는 거", meaning: "여기 아이디어는 한 번 저장해서 재사용하는 거예요.", model: "The idea here is to store it once and reuse it.", core: false },
      { key: "iv:rfx:narrate#7", cue: "빨리 확인할게 · 이게 되는지 · 넘어가기 전에", meaning: "넘어가기 전에 이게 되는지 빨리 확인할게요.", model: "Let me quickly check this works before I move on.", core: false },
      { key: "iv:rfx:narrate#8", cue: "좋아요 · 그 부분은 돼요 · 그래서 · 이제 · 넘어갈게 · 다음 단계로", meaning: "좋아요, 이 부분은 되니까, 이제 다음 단계로 넘어갈게요.", model: "Okay, that part works, so now let me move to the next step.", core: false },
    ],
  },
  {
    id: "explain",
    labelEn: "Explaining intent",
    labelKo: "의도 설명",
    cards: [
      { key: "iv:rfx:explain#0", cue: "그래서 · 이게 하는 일은 · 입력을 받아서 · 결과를 돌려주는 거", meaning: "이게 하는 일은, 입력을 받아서 결과를 돌려주는 거예요.", model: "So what this does is, it takes the input and returns the result.", core: false },
      { key: "iv:rfx:explain#1", cue: "이 부분은 · 검증을 처리하고 · 그다음 · 저장해", meaning: "이 부분은 검증을 처리하고, 그다음 저장해요.", model: "This part handles the validation, and then we save it.", core: false },
      { key: "iv:rfx:explain#2", cue: "나 이렇게 하는 건 · 왜냐면 · 테스트하기 더 쉬워서", meaning: "이렇게 하는 이유는 테스트하기 더 쉬워서예요.", model: "I'm doing it this way because it's easier to test.", core: false },
      { key: "iv:rfx:explain#3", cue: "내가 · 이걸 따로 빼낸 이유는 · 로직을 반복하지 않으려고", meaning: "이걸 따로 빼낸 이유는 로직을 반복하지 않으려고요.", model: "The reason I split this out is to avoid repeating the logic.", core: false },
      { key: "iv:rfx:explain#4", cue: "지금은 · 이게 · 그냥 null을 반환하지만 · 채워 넣을 거 · 다음에", meaning: "지금은 그냥 null을 반환하지만, 다음에 채워 넣을게요.", model: "Right now this just returns null, but I'll fill it in next.", core: false },
      { key: "iv:rfx:explain#5", cue: "그래서 · 이 시점에는 · 우리 이미 알고 있어 · 값이 유효하다는 걸", meaning: "그래서 이 시점에는, 값이 유효하다는 걸 이미 알고 있어요.", model: "So at this point, we already know the value is valid.", core: false },
      { key: "iv:rfx:explain#6", cue: "설명해 드릴게 · 어떤 일이 일어나는지 · 단계별로", meaning: "어떤 일이 일어나는지 단계별로 설명해 드릴게요.", model: "Let me walk you through what happens step by step.", core: false },
    ],
  },
  {
    id: "datastructure",
    labelEn: "Data structure & design",
    labelKo: "자료구조 & 설계",
    cards: [
      { key: "iv:rfx:datastructure#0", cue: "쓸게요 · Map · List보다 · 여기 · 조회가 · O(1) 유지되게 · O(n) 대신", meaning: "여기는 List보다 Map을 쓸게요. 조회가 O(n) 대신 O(1)로 유지되게요.", model: "I'll use a Map over a List here, so the lookup stays O(1) instead of O(n).", core: false },
      { key: "iv:rfx:datastructure#1", cue: "둘 다 · 되긴 해요 · 하지만 · 가겠어요 · 이걸로 · 읽기 쉬워서 · 더", meaning: "둘 다 되긴 하는데, 더 읽기 쉬워서 이걸로 갈게요.", model: "Both would work, but I'll go with this one because it reads cleaner.", core: false },
      { key: "iv:rfx:datastructure#2", cue: "쓸게요 · Deque · 넣고 뺄 수 있게 · 양쪽 끝에서 · 싸게", meaning: "양쪽 끝에서 싸게 넣고 빼야 해서 Deque를 쓸게요.", model: "I'll use a Deque so I can add and remove from both ends cheaply.", core: false },
      { key: "iv:rfx:datastructure#3", cue: "List · 충분해요 · 이곳에 · 왜냐면 · 필요 없거든 · 빠른 조회가", meaning: "빠른 조회가 필요 없어서 여기는 그냥 List면 충분해요.", model: "A plain List is enough here, since I don't need fast lookup.", core: false },
      { key: "iv:rfx:datastructure#4", cue: "트레이드오프는 · 더 많은 메모리 · 지금 · 더 빠른 조회 위해 · 나중에", meaning: "트레이드오프는, 지금 메모리를 더 쓰고 나중에 조회를 더 빠르게 하는 거예요.", model: "The trade-off is more memory now for faster lookups later.", core: false },
      { key: "iv:rfx:datastructure#5", cue: "필요했다면 · 접두사 검색 · 쓸 거예요 · Trie · 대신", meaning: "접두사 검색이 필요했다면, 대신 Trie를 썼을 거예요.", model: "If we needed prefix search, I'd use a Trie instead.", core: false },
      { key: "iv:rfx:datastructure#6", cue: "시작하고 · 단순한 구조로 · 바꿀게요 · 그걸 · 느려지면", meaning: "일단 단순한 구조로 시작하고, 느려지면 바꿀게요.", model: "Let me start with the simple structure, and I'll swap it if it gets slow.", core: false },
    ],
  },
  {
    id: "edge",
    labelEn: "Edge cases & correctness",
    labelKo: "엣지 & 정확성",
    cards: [
      { key: "iv:rfx:edge#0", cue: "생각해 볼게요 · 엣지 케이스들을 · 여기서", meaning: "여기서 엣지 케이스들을 생각해 볼게요.", model: "Let me think about the edge cases here.", core: true },
      { key: "iv:rfx:edge#1", cue: "어떻게 동작해야 하나요? · 입력이 비어 있거나 null이면", meaning: "입력이 비어 있거나 null이면 어떻게 동작해야 하죠?", model: "What should happen if the input is empty or null?", core: false },
      { key: "iv:rfx:edge#2", cue: "확인하고 싶어요 · 우리가 처리하는지 · 중복을 · 제대로", meaning: "중복을 제대로 처리하는지 확인하고 싶어요.", model: "I want to make sure we handle duplicates correctly.", core: false },
      { key: "iv:rfx:edge#3", cue: "한 가지 · 제가 신경 쓸 건 · 0이냐 · 값 없음이냐", meaning: "제가 신경 쓸 부분은 0이냐 값이 없냐 하는 거예요.", model: "One thing I'd watch for is zero versus missing.", core: false },
      { key: "iv:rfx:edge#4", cue: "이건 오버플로 날 수 있어요 · 큰 입력에서는 · 그래서 long을 쓸게요 · 여기서", meaning: "큰 입력에서는 오버플로가 날 수 있어서, 여기선 long을 쓸게요.", model: "This could overflow for large inputs, so I'll use a long here.", core: false },
      { key: "iv:rfx:edge#5", cue: "중요한가요? · 결과의 순서가 · 여기서", meaning: "여기서 결과의 순서가 중요한가요?", model: "Does the order of the results matter here?", core: false },
      { key: "iv:rfx:edge#6", cue: "이게 병렬로 돌아간다면 · 우리는 고려해야 할 거예요 · 동시성을", meaning: "이게 병렬로 돌아간다면, 동시성을 고려해야 할 거예요.", model: "If this runs in parallel, we'd need to think about concurrency.", core: false },
    ],
  },
  {
    id: "testing",
    labelEn: "Testing & running",
    labelKo: "테스트 & 실행",
    cards: [
      { key: "iv:rfx:testing#0", cue: "넣을게요 · 빠른 테스트를 · main에 · 그리고 돌려볼게요", meaning: "main에 빠른 테스트 하나 넣고 돌려볼게요.", model: "Let me add a quick test in main and run it.", core: true },
      { key: "iv:rfx:testing#1", cue: "시작할게요 · 정상 케이스부터 · 그다음 · 추가할게요 · 엣지 케이스를", meaning: "먼저 정상 케이스부터 하고, 그다음에 엣지 케이스를 추가할게요.", model: "Let me start with the happy path, then I'll add the edge cases.", core: false },
      { key: "iv:rfx:testing#2", cue: "네 · 돌려볼게요 · 그리고 봐볼게요 · 우리가 뭘 얻는지", meaning: "자, 한번 돌려서 결과를 볼게요.", model: "Okay, let me run it and see what we get.", core: false },
      { key: "iv:rfx:testing#3", cue: "통과했어요 · 그래서 · 기본 케이스는 · 동작합니다", meaning: "통과했네요. 기본 케이스는 동작합니다.", model: "It passed, so the basic case works.", core: false },
      { key: "iv:rfx:testing#4", cue: "그건 아니에요 · 제가 예상한 게 · 한번 살펴볼게요", meaning: "예상한 결과가 아니네요. 한번 살펴볼게요.", model: "That's not what I expected, let me take a look.", core: false },
      { key: "iv:rfx:testing#5", cue: "이제 · 시도해 볼게요 · 빈 입력을 · 안전하게", meaning: "이제 안전하게 빈 입력도 한번 넣어볼게요.", model: "Now let me try an empty input to be safe.", core: false },
    ],
  },
  {
    id: "debug",
    labelEn: "Debugging out loud",
    labelKo: "디버깅",
    cards: [
      { key: "iv:rfx:debug#0", cue: "넣을게요 · 프린트를 · 여기에 · 보려고 · 그 실제 값을", meaning: "실제 값을 보려고 여기에 print를 하나 넣을게요.", model: "I'll add a print here to see the actual value.", core: true },
      { key: "iv:rfx:debug#1", cue: "오케이 · 그 값이 · 아니에요 · 제가 예상한 것과", meaning: "음, 값이 제가 예상한 것과 다르네요.", model: "Okay, the value is not what I expected.", core: false },
      { key: "iv:rfx:debug#2", cue: "좁혀볼게요 · 그걸 · 한 부분으로 · 먼저", meaning: "먼저 한 부분으로 범위를 좁혀볼게요.", model: "Let me narrow it down to one part first.", core: false },
      { key: "iv:rfx:debug#3", cue: "에러가 · 말해요 · 널이라고 · 바로 여기서", meaning: "에러를 보니 바로 여기서 null이라고 나오네요.", model: "The error says it's null right here.", core: false },
      { key: "iv:rfx:debug#4", cue: "그래서 · 문제가 · 오고 있어요 · 이 함수에서", meaning: "그래서 문제는 이 함수에서 오고 있어요.", model: "So the problem is coming from this function.", core: false },
      { key: "iv:rfx:debug#5", cue: "좋아요 · 그게 · 고쳤어요 · 출력이 · 맞게 나와요 · 지금", meaning: "좋아요, 그게 고쳤네요. 이제 출력이 맞게 나와요.", model: "Good, that fixed it, the output looks right now.", core: false },
    ],
  },
  {
    id: "tradeoff",
    labelEn: "Trade-offs & production",
    labelKo: "트레이드오프 & 프로덕션",
    cards: [
      { key: "iv:rfx:tradeoff#0", cue: "단순하게 가고 있어요 · 이걸 · 지금은 · 하지만 프로덕션에선 · 내릴 거예요 · 이걸 · 데이터베이스로", meaning: "지금은 단순하게 가는데, 프로덕션에선 이걸 데이터베이스로 내릴 거예요.", model: "I'm keeping this simple for now, but in production I'd push this down to the database.", core: true },
      { key: "iv:rfx:tradeoff#1", cue: "진짜 보장은 · 나와야 해요 · 유니크 제약에서 · 애플리케이션 코드가 아니라", meaning: "진짜 보장은 애플리케이션 코드가 아니라 유니크 제약에서 나와야 해요.", model: "The real guarantee should come from a unique constraint, not from the application code.", core: true },
      { key: "iv:rfx:tradeoff#2", cue: "여러 노드에 걸쳐선 · 인메모리 체크는 · 안 통하니까 · 데이터베이스가 · 기준이 돼야 해요", meaning: "노드가 여러 개면 인메모리 체크는 안 통하니까, 데이터베이스가 기준이 돼야 해요.", model: "Across multiple nodes, the in-memory check doesn't hold, so the database has to be the source of truth.", core: false },
      { key: "iv:rfx:tradeoff#3", cue: "이건 · 재시도될 수 있으니까 · 원해요 · 연산이 · 멱등하길", meaning: "이건 재시도될 수 있으니까, 연산이 멱등하게 만들고 싶어요.", model: "Since this can be retried, I want the operation to be idempotent.", core: true },
      { key: "iv:rfx:tradeoff#4", cue: "차라리 · 단순하고 정확하게 가는 게 나아요 · ~보다 · 똑똑하지만 깨지기 쉬운 것", meaning: "똑똑하지만 깨지기 쉬운 것보다, 단순해도 정확한 쪽이 나아요.", model: "I'd rather keep it simple and correct than clever and fragile.", core: false },
      { key: "iv:rfx:tradeoff#5", cue: "생각 안 해요 · 우리가 과하게 설계할 필요 있다고 · 이걸 · 아직 · 추가하면 돼요 · 실제로 부딪히면 · 그 한계에", meaning: "이건 아직 과하게 설계할 필요 없어요; 실제로 그 한계에 부딪히면 추가하면 돼요.", model: "I don't think we need to over-engineer this yet; we can add it when we actually hit that limit.", core: false },
      { key: "iv:rfx:tradeoff#6", cue: "최적화하기 전에 · 뭐든 · 측정하고 싶어요 · 어디서 · 시간이 · 실제로 · 가는지", meaning: "뭔가 최적화하기 전에, 시간이 실제로 어디서 쓰이는지 먼저 측정하고 싶어요.", model: "Before I optimize anything, I'd want to measure where the time actually goes.", core: false },
      { key: "iv:rfx:tradeoff#7", cue: "프로덕션에선 · 넣을 거예요 · 트레이스 아이디랑 · 구조화된 로그를 · 그래서 우리가 · 실제로 · 디버깅할 수 있게 · 이걸 · 나중에", meaning: "프로덕션에선 트레이스 아이디랑 구조화된 로그를 넣어서, 나중에 실제로 디버깅할 수 있게 할 거예요.", model: "In production I'd add a trace id and a structured log, so we can actually debug this later.", core: false },
    ],
  },
  {
    id: "feedback",
    labelEn: "Hints, feedback & disagreement",
    labelKo: "힌트·피드백·이견",
    cards: [
      { key: "iv:rfx:feedback#0", cue: "그거 좋은 지적이네 · 한번 해볼게 · 그렇게", meaning: "좋은 지적이네요. 그렇게 해볼게요.", model: "That's a good point — let me try that.", core: false },
      { key: "iv:rfx:feedback#1", cue: "알겠어 · 무슨 말인지 · 다시 생각해볼게 · 이거", meaning: "무슨 말씀인지 알겠어요. 다시 생각해볼게요.", model: "I see what you mean. Let me rethink this.", core: false },
      { key: "iv:rfx:feedback#2", cue: "난 사실 · 반대로 가고 싶어 · 그리고 여기 그 이유가", meaning: "저는 사실 반대로 가고 싶은데, 이유를 말씀드릴게요.", model: "I'd actually go the other way, and here's why.", core: false },
      { key: "iv:rfx:feedback#3", cue: "우리 한번 해봐도 될까? · 이렇게 · 대신에", meaning: "대신 이런 식으로 한번 해봐도 될까요?", model: "Could we maybe try it this way instead?", core: false },
      { key: "iv:rfx:feedback#4", cue: "그래 좋아 · 그걸로 가자", meaning: "맞는 말씀이에요. 그걸로 가시죠.", model: "Fair enough — let's go with that.", core: false },
    ],
  },
  {
    id: "stuck",
    labelEn: "Getting stuck & recovering",
    labelKo: "막힘·시간벌기·회복",
    cards: [
      { key: "iv:rfx:stuck#0", cue: "생각해 볼게요 · 그거 · 한 초 동안", meaning: "잠깐 그거 좀 생각해 볼게요.", model: "Let me think about that for a second.", core: true },
      { key: "iv:rfx:stuck#1", cue: "저 살짝 막혔어요 · 여기서 · 돌아갈게요", meaning: "여기서 살짝 막혔는데, 잠깐 돌아갈게요.", model: "I'm a little stuck here, let me back up.", core: true },
      { key: "iv:rfx:stuck#2", cue: "줄 수 있어요? · 저한테 · 힌트를 · 시작할 수 있게", meaning: "시작할 수 있게 힌트 좀 주실 수 있을까요?", model: "Can you give me a hint to get started?", core: true },
      { key: "iv:rfx:stuck#3", cue: "죄송해요 · 시작할게요 · 그걸 · 처음부터 다시", meaning: "죄송해요, 그거 처음부터 다시 말할게요.", model: "Sorry, let me start that over.", core: false },
      { key: "iv:rfx:stuck#4", cue: "말해 볼게요 · 그걸 · 다르게", meaning: "그거 다르게 한번 말해 볼게요.", model: "Let me say that a different way.", core: false },
      { key: "iv:rfx:stuck#5", cue: "제가 와 있는 곳은 · 지금 · 이거예요", meaning: "지금 제가 와 있는 지점은 이거예요.", model: "So where I am right now is this.", core: false },
    ],
  },
  {
    id: "airound",
    labelEn: "AI-allowed round",
    labelKo: "AI 라운드",
    cards: [
      { key: "iv:rfx:airound#0", cue: "프롬프트하기 전에 · 나는 좋아해요 · 나누는 걸 · 문제를 · 작은 조각들로 · 직접", meaning: "프롬프트 보내기 전에, 문제를 직접 작은 조각들로 나누는 걸 좋아해요.", model: "Before I prompt, I like to break the problem into small pieces myself.", core: false },
      { key: "iv:rfx:airound#1", cue: "말할 거예요 · AI에게 · 정확히 뭘 원하는지 · 그래서 · 이끌고 있어요 · 그걸 · 따라가는 게 아니라 · 그걸", meaning: "AI한테 원하는 걸 정확히 말할 거예요. 따라가는 게 아니라 제가 끌고 가게요.", model: "I'll tell the AI exactly what I want, so I'm guiding it, not following it.", core: false },
      { key: "iv:rfx:airound#2", cue: "항상 읽어요 · 코드를 · 실행하기 전에 · 그걸 · 안 믿어요 · 그걸 · 무작정", meaning: "실행하기 전에 항상 코드를 읽어요. 무작정 믿지 않아요.", model: "I always read the code before I run it. I don't trust it blindly.", core: true },
      { key: "iv:rfx:airound#3", cue: "맞아 보여요 · 그런데 · 검증하고 싶어요 · 그 부분을 · 다루는 · 중복을", meaning: "맞아 보이긴 하는데, 중복을 처리하는 부분을 검증하고 싶어요.", model: "It looks right, but I want to verify the part that handles duplicates.", core: false },
      { key: "iv:rfx:airound#4", cue: "AI가 놓쳤어요 · 이 케이스를 · 그래서 · 고칠게요 · 그걸 · 직접", meaning: "AI가 이 케이스를 놓쳤네요. 그건 제가 직접 고칠게요.", model: "The AI missed this case, so let me fix that myself.", core: false },
      { key: "iv:rfx:airound#5", cue: "유지하겠어요 · 구조를 · AI가 준 · 그런데 · 설계 결정은 · 제 거예요", meaning: "구조는 AI가 준 걸 유지하겠지만, 설계 결정은 제 거예요.", model: "I'll keep the structure it gave me, but the design decision is mine.", core: false },
      { key: "iv:rfx:airound#6", cue: "써요 · AI를 · 더 빠르게 가려고 · 그런데 · 여전히 책임져요 · 모든 줄을", meaning: "AI는 속도를 높이려고 쓰는 거고, 모든 줄은 여전히 제가 책임져요.", model: "I use the AI to go faster, but I still own every line.", core: true },
    ],
  },
  {
    id: "glue",
    labelEn: "ESL glue & transitions",
    labelKo: "연결어·전환",
    cards: [
      { key: "iv:rfx:glue#0", cue: "네 · 그거 · 말 되네", meaning: "네, 그거 말 되네요.", model: "Yeah, that makes sense.", core: true },
      { key: "iv:rfx:glue#1", cue: "좋아요 · 넘어갈게 · 다음 부분으로", meaning: "좋아요, 다음 부분으로 넘어갈게요.", model: "Okay, let me move on to the next part.", core: false },
      { key: "iv:rfx:glue#2", cue: "그러니까 · 제가 보기엔", meaning: "그러니까, 제가 보기엔...", model: "So, the way I see it is...", core: false },
      { key: "iv:rfx:glue#3", cue: "죄송한데 · 말씀해 주실래요? · 그거 · 다시", meaning: "죄송한데, 다시 한 번 말씀해 주실래요?", model: "Sorry, could you say that again?", core: true },
      { key: "iv:rfx:glue#4", cue: "확인차 · 제가 이해했는지 · 그거 · 제대로", meaning: "제가 제대로 이해했는지 확인차...", model: "Just to make sure I got that right...", core: false },
      { key: "iv:rfx:glue#5", cue: "이해되세요 · 여기까지?", meaning: "여기까지 이해되시나요?", model: "Does that make sense so far?", core: false },
      { key: "iv:rfx:glue#6", cue: "돌아갈게 · 잠깐", meaning: "잠깐 다시 앞으로 돌아갈게요.", model: "Let me back up for a second.", core: false },
    ],
  },
  {
    id: "closing",
    labelEn: "Closing & wrap-up",
    labelKo: "마무리",
    cards: [
      { key: "iv:rfx:closing#0", cue: "정리하자면 · 저는 만들었어요 · 도메인 RAG 시스템을 · 그리고 출시했어요 · 그걸 · 제대로 된 평가와 함께", meaning: "정리하자면, 저는 도메인 RAG 시스템을 만들고 제대로 된 평가까지 붙여서 출시했습니다.", model: "So to sum up, I built a domain RAG system and shipped it with proper evals.", core: false },
      { key: "iv:rfx:closing#1", cue: "만약 제가 시간이 더 있었다면 · 다음으로 제가 추가할 건 · 바로 · 더 나은 검색 평가예요", meaning: "시간이 더 있었다면, 다음으로 추가할 건 더 나은 검색 평가였을 거예요.", model: "If I had more time, the next thing I'd add is better retrieval evals.", core: false },
      { key: "iv:rfx:closing#2", cue: "이건 정말 도움이 됐어요 · 고마워요 · 날 차근차근 설명해 줘서", meaning: "정말 도움이 됐습니다. 설명해 주셔서 감사해요.", model: "This was really helpful, thanks for walking me through it.", core: false },
      { key: "iv:rfx:closing#3", cue: "전 좋아요 · 더 깊이 들어가도 · 이 중 아무거나 · 만약 그게 유용하다면", meaning: "원하시면 어느 부분이든 더 깊이 들어갈 수 있습니다.", model: "I'm happy to go deeper on any of this if that's useful.", core: false },
      { key: "iv:rfx:closing#4", cue: "뭔가 있을까요? · 당신이 제가 명확히 해주길 바라는 · 우리가 마무리하기 전에?", meaning: "마무리하기 전에 더 명확히 설명드릴 부분이 있을까요?", model: "Is there anything you'd like me to clarify before we wrap up?", core: false },
      { key: "iv:rfx:closing#5", cue: "전 정말 신나요 · 이 역할에 대해 · 그래서 좋겠어요 · 우리가 계속 얘기할 수 있으면", meaning: "이 자리에 정말 관심이 많아서, 계속 이야기 나눌 수 있으면 좋겠습니다.", model: "I'm really excited about this role, so I hope we can keep talking.", core: false },
    ],
  },
];

/** All 107 reflex cards, flattened. */
export const REFLEX_CARDS: ReflexCard[] = REFLEX_CLUSTERS.flatMap((c) => c.cards);

/** The ~18 survival reflexes that must be automatic ("자다가도 튀어나오게"). */
export const CORE_REFLEX: ReflexCard[] = REFLEX_CARDS.filter((c) => c.core);

export const INTERVIEW_CONCEPTS: InterviewCard[] = [
  { key: "iv:cpt:optimistic-vs-pessimistic-locking", group: "concept", title: "Optimistic vs Pessimistic Locking", cue: "낙관적 락 vs 비관적 락을 영어로 설명해봐 — 정의 + 짧은 예시 + 트레이드오프", model: "Both stop two writers from stepping on each other, but they bet differently. Pessimistic locking grabs the row up front with something like SELECT FOR UPDATE, so nobody else can touch it until I'm done. Optimistic locking takes no lock — it keeps a version column, checks it on write, and if the version moved, I retry. For my inventory updates I usually go optimistic when conflicts are rare, since it keeps throughput high. But under heavy contention the retries pile up and you waste work, so for a hot row I'd rather take a pessimistic lock and just serialize cleanly.", note: "version column = 버전 컬럼. SELECT FOR UPDATE를 자연스럽게 발음할 것.", concepts: ["concurrency", "locking", "data-correctness"] },
  { key: "iv:cpt:transaction-acid-isolation", group: "concept", title: "Transaction / ACID / Isolation Level", cue: "트랜잭션 / ACID / 격리 수준을 영어로 설명해봐 — 정의 + 짧은 예시 + 트레이드오프", model: "A transaction is a group of operations that either all commit or all roll back, and ACID is just the four guarantees around that — atomic, consistent, isolated, durable. The isolation level controls how much one in-flight transaction can see another's uncommitted work. For example, when I move stock between two warehouses, the decrement and the increment have to be one atomic unit, or my totals go wrong. The trade-off is safety versus speed: serializable is the strictest but it locks more and slows you down, so most of the time I sit at read committed or repeatable read, and I only tighten it where a real anomaly would corrupt the numbers.", note: "anomaly = 이상현상(dirty read 등). 격리 레벨 이름들 또박또박.", concepts: ["transactions", "acid", "isolation", "data-correctness"] },
  { key: "iv:cpt:race-condition-deadlock", group: "concept", title: "Race Condition / Deadlock", cue: "레이스 컨디션 / 데드락을 영어로 설명해봐 — 정의 + 짧은 예시 + 트레이드오프", model: "A race condition is when the outcome depends on timing — two threads interleave in a way you didn't plan for, and the result is wrong. A deadlock is a different kind of stuck: two transactions each hold a lock the other needs, so neither can move. A classic race in my world is two requests both reading a stock count of one and both selling it, so I oversell. The fix is usually a unique constraint or a lock — but the moment you add locks, you open the door to deadlocks, so I keep lock ordering consistent and let the database detect and kill one side rather than hold locks forever.", note: "interleave = 끼어들어 섞이다. oversell = 초과 판매.", concepts: ["concurrency", "race-condition", "deadlock"] },
  { key: "iv:cpt:idempotency", group: "concept", title: "Idempotency", cue: "멱등성을 영어로 설명해봐 — 정의 + 짧은 예시 + 트레이드오프", model: "Idempotency means running the same operation more than once has the same effect as running it once. It matters anywhere a client might retry, because networks drop responses all the time. In payments I attach an idempotency key to each charge, so if the caller retries after a timeout, I look up the key, see I already processed it, and return the original result instead of charging twice. The trade-off is you have to store and check those keys, which costs a little storage and a lookup on every write — but that's cheap next to double-charging a customer or double-counting inventory.", note: "idempotency key = 멱등 키. 'once' 강세.", concepts: ["idempotency", "reliability", "payments"] },
  { key: "iv:cpt:state-machine", group: "concept", title: "State Machine", cue: "상태 머신을 영어로 설명해봐 — 정의 + 짧은 예시 + 트레이드오프", model: "A state machine is a model where an entity is always in exactly one well-defined state, and only certain transitions between states are allowed. It's great for anything with a lifecycle. An order in my system goes created, paid, shipped, delivered — and you can't jump from created straight to delivered, so I encode the legal transitions and reject everything else. The benefit is the rules live in one place and illegal states just can't happen. The trade-off is rigidity — when the business adds a step like returned or refunded, you have to update the machine carefully instead of sprinkling if-statements around the code.", note: "transition = 전이. lifecycle = 수명주기. 차분하게 단계 나열.", concepts: ["state-machine", "modeling", "correctness"] },
  { key: "iv:cpt:source-of-truth-audit-log", group: "concept", title: "Source of Truth / Audit Log", cue: "단일 진실 공급원 / 감사 로그를 영어로 설명해봐 — 정의 + 짧은 예시 + 트레이드오프", model: "The source of truth is the one system you trust when copies disagree — everything else is a cache or a projection of it. An audit log is the append-only record of every change, so you can always reconstruct how you got to the current state. In my work the ledger is the source of truth for balances, and the audit log lets me answer not just what the number is, but why it changed and who changed it. The trade-off is discipline and storage — every change has to go through the source of truth, and you can never let a side path quietly edit data, or the audit trail starts lying to you.", note: "append-only = 추가만 가능. projection = 파생 뷰. ledger 강조.", concepts: ["source-of-truth", "audit-log", "data-correctness"] },
  { key: "iv:cpt:reconciliation", group: "concept", title: "Reconciliation", cue: "정합성 대조(리컨실리에이션)를 영어로 설명해봐 — 정의 + 짧은 예시 + 트레이드오프", model: "Reconciliation is comparing two independent records that should agree, and resolving any difference. This is really the core of my career — making the system's numbers match reality. A concrete example: every night I take the physical inventory count and diff it against what the ledger says we should have, and every mismatch becomes a discrepancy I either explain or correct. The trade-off is timing and cost — real-time reconciliation catches drift immediately but it's expensive and noisy, so usually I batch it on a schedule and accept that I'm catching problems hours later instead of right away.", note: "diff = 대조하다(동사). discrepancy = 불일치. drift = 점진적 어긋남. 본인 강점이므로 자신감 있게.", concepts: ["reconciliation", "data-correctness", "inventory-ledger"] },
  { key: "iv:cpt:unique-constraint-upsert", group: "concept", title: "Unique Constraint / Upsert", cue: "유니크 제약 / 업서트를 영어로 설명해봐 — 정의 + 짧은 예시 + 트레이드오프", model: "A unique constraint is the database enforcing that a column, or a combination of columns, only shows up once — it's your last line of defense against duplicates. An upsert is insert-or-update in one atomic step: insert if it's new, otherwise update the existing row. I lean on these together — a unique key on something like transaction ID, plus an upsert, means even if a message gets delivered twice, the second one just updates instead of creating a phantom record. The trade-off is the constraint rejects writes at the database level, so the application has to handle that conflict gracefully instead of blowing up, and a busy unique index does add a little write cost.", note: "upsert = INSERT ... ON CONFLICT. last line of defense = 최후의 방어선.", concepts: ["constraints", "upsert", "deduplication"] },
  { key: "iv:cpt:indexing-query-performance", group: "concept", title: "Indexing / Query Performance", cue: "인덱싱 / 쿼리 성능을 영어로 설명해봐 — 정의 + 짧은 예시 + 트레이드오프", model: "An index is a separate sorted structure that lets the database find rows without scanning the whole table. You add one to match how you actually query. For example, my reconciliation job filters by account and date range constantly, so a composite index on those two turns a full table scan into a quick range lookup. The trade-off is that every index has to be maintained on writes and it costs storage, so you don't just index everything — I check the query plan, index the hot paths, and drop indexes nothing uses.", note: "composite index = 복합 인덱스. query plan = 실행 계획(EXPLAIN). full table scan 대비 강조.", concepts: ["indexing", "performance", "databases"] },
  { key: "iv:cpt:queue-worker-retry-dlq", group: "concept", title: "Queue / Worker / Retry / DLQ", cue: "큐 / 워커 / 재시도 / DLQ를 영어로 설명해봐 — 정의 + 짧은 예시 + 트레이드오프", model: "A queue decouples producers from consumers — work goes in, and workers pull it off and process it at their own pace. When a worker fails, you retry, usually with backoff, and if it keeps failing, the message goes to a dead-letter queue so it stops blocking the line. In my world I'd push reconciliation tasks onto a queue, let a pool of workers chew through them, and route the poison messages to a DLQ to look at later. The trade-off is you swap a simple synchronous flow for eventual processing and more moving parts — now you have to watch queue depth, retry storms, and that DLQ, or failures pile up silently.", note: "backoff = 점증 대기. poison message = 계속 실패하는 메시지. queue depth = 큐 적체량.", concepts: ["queues", "workers", "retry", "dlq"] },
  { key: "iv:cpt:outbox-at-least-once-dedup", group: "concept", title: "Outbox / At-Least-Once / Deduplication", cue: "아웃박스 / at-least-once / 중복 제거를 영어로 설명해봐 — 정의 + 짧은 예시 + 트레이드오프", model: "The outbox pattern solves the dual-write problem. Instead of writing to my database and publishing a message separately — and risking one succeeding without the other — I write the event into an outbox table in the same transaction, and a relay publishes it afterward. That gives you at-least-once delivery: the message will arrive, but it might arrive more than once. So the consumer has to deduplicate, usually by tracking which event IDs it's already handled. The trade-off is you accept duplicates and push the work onto idempotent consumers, but in exchange you never lose an event or let your ledger and your event stream drift apart.", note: "dual-write problem = 이중 쓰기 문제. relay = 중계 발행기. at-least-once 또박또박.", concepts: ["outbox", "messaging", "deduplication", "consistency"] },
  { key: "iv:cpt:observability", group: "concept", title: "Observability (Structured Log / Trace ID / Metric)", cue: "옵저버빌리티(구조화 로그 / 트레이스 ID / 메트릭)를 영어로 설명해봐 — 정의 + 짧은 예시 + 트레이드오프", model: "Observability is being able to understand what your system is doing from the outside, and it rests on three things: structured logs, traces, and metrics. Structured logs are machine-parseable key-value events instead of free text, a trace ID stitches one request across every service it touches, and metrics are the aggregate numbers you watch and alert on. When a reconciliation run produces a wrong total, I follow the trace ID through every hop to find exactly where the number went bad, instead of guessing. The trade-off is overhead and cost — logging and tracing everything is expensive and noisy, so you sample, and you log with intent rather than instrumenting blindly.", note: "structured log = 구조화 로그. trace ID = 추적 ID. stitch across = 묶다. sample = 표본 추출.", concepts: ["observability", "logging", "tracing", "metrics"] },
];

export const INTERVIEW_FRAMES: InterviewCard[] = [
  { key: "iv:frm:frame-what-im-doing", group: "frame", title: "\"What I'm doing here is ___.\"", cue: "코딩을 시작하면서 지금 작성하는 코드 블록이 무슨 역할인지 페어에게 한 줄로 알려줄 때", model: "What I'm doing here is loading both sides — the physical count and the ledger balance — so I can compare them in one pass.", note: "현재진행형으로 '지금' 하는 일을 짚어줄 때. 'here'가 코드의 특정 지점을 가리킴.", concepts: ["narration", "present-continuous", "reconciliation"] },
  { key: "iv:frm:frame-plan-first-then", group: "frame", title: "\"My plan is to ___ first, then ___.\"", cue: "본격적으로 타이핑하기 전에 접근 순서를 먼저 설명할 때", model: "My plan is to build a lookup of the ledger entries first, then walk the inventory once and flag anything that doesn't match.", note: "큰 그림을 두 단계로 쪼개 보여줄 때. 면접관이 방향을 따라오기 쉬워짐.", concepts: ["planning", "sequencing"] },
  { key: "iv:frm:frame-using-because-need", group: "frame", title: "\"I'm using a ___ here because I need ___.\"", cue: "특정 자료구조를 고른 이유(빠른 조회 / 정렬 / 중복 제거 등)를 즉석에서 정당화할 때", model: "I'm using a HashMap here because I need constant-time lookups by SKU when I match each inventory row against the ledger.", note: "자료구조 + 그게 주는 성질(lookup/ordering/dedup)을 한 문장에 묶는 게 핵심. 말로 할 땐 'O(1)'보다 'constant-time'이 자연스럽게 들림.", concepts: ["data-structures", "justification", "complexity"] },
  { key: "iv:frm:frame-chose-over-because", group: "frame", title: "\"I chose ___ over ___ because ___.\"", cue: "두 선택지 중 하나를 골랐고 그 이유를 밝힐 때 (예: HashMap vs TreeMap)", model: "I chose a HashMap over a TreeMap because I don't need the keys sorted — I just need fast lookups while I match records.", note: "버린 쪽을 명시하면 '대안을 알고도 골랐다'는 신호가 됨.", concepts: ["trade-offs", "decision-making"] },
  { key: "iv:frm:frame-this-part-and-then", group: "frame", title: "\"This part ___, and then ___.\"", cue: "방금 쓴 코드 한 덩어리가 무엇을 하고 그 다음 무슨 일이 일어나는지 흐름을 짚을 때", model: "This part groups the transactions by account, and then the next loop sums each group so the totals line up with the ledger.", note: "코드를 읽어 내려가며 '여기는 ~하고 그담은 ~한다' 식으로 흐름을 중계할 때.", concepts: ["code-walkthrough", "control-flow"] },
  { key: "iv:frm:frame-check-handle", group: "frame", title: "\"This check is here to handle ___.\"", cue: "방어 코드나 if 분기를 넣은 뒤, 그게 어떤 상황을 막는지 설명할 때", model: "This check is here to handle the case where the ledger has an entry but the physical record is missing — otherwise the count would quietly drift out of sync.", note: "엣지 케이스를 먼저 의식하고 있다는 걸 보여주는 좋은 신호.", concepts: ["edge-cases", "defensive-coding", "data-correctness"] },
  { key: "iv:frm:frame-trade-off-versus", group: "frame", title: "\"The trade-off here is ___ versus ___.\"", cue: "지금 내린 선택에 따라오는 비용과 이득을 솔직하게 짚을 때", model: "The trade-off here is memory versus speed — I'm holding the whole ledger in a map, but that's what lets me reconcile in a single pass.", note: "'versus' 양쪽을 짧고 대칭적으로. 한쪽을 깎아 다른 쪽을 샀다는 톤.", concepts: ["trade-offs", "memory-vs-speed"] },
  { key: "iv:frm:frame-simple-for-now-production", group: "frame", title: "\"I'm keeping it simple for now — in production I'd ___.\"", cue: "면접용으로 일부러 단순하게 짜면서, 실서비스였다면 어떻게 달랐을지 덧붙일 때", model: "I'm keeping it simple for now — in production I'd stream the ledger from the DB in batches instead of loading all of it into memory.", note: "'지금은 일부러 단순' + '진짜였다면 ~' 구조. 시야가 넓다는 인상을 줌.", concepts: ["scoping", "production-awareness"] },
  { key: "iv:frm:frame-case-im-worried", group: "frame", title: "\"The case I'm worried about is ___.\"", cue: "아직 안 짠 부분 중에 위험하다고 느끼는 지점을 미리 입 밖으로 꺼낼 때", model: "The case I'm worried about is duplicate transaction IDs — if the same entry gets counted twice, the balance won't match reality.", note: "걱정을 미리 말하면 협업적으로 보이고, 페어가 같이 고민하게 됨.", concepts: ["risk-awareness", "edge-cases", "data-correctness"] },
  { key: "iv:frm:frame-make-sure-stays-correct", group: "frame", title: "\"I want to make sure ___ stays correct.\"", cue: "정확성이 핵심인 지점에서, 무엇을 끝까지 지켜야 하는지 못 박을 때", model: "I want to make sure the running total stays correct even if the entries arrive out of order — that's really the whole point of reconciliation.", note: "그의 시그니처 강점(데이터 정확성)을 자연스럽게 드러내는 프레임.", concepts: ["data-correctness", "invariants"] },
];

export const INTERVIEW_SCENARIOS: InterviewCard[] = [
  { key: "iv:scn:prevent-double-payment", group: "scenario", sub: "interview", title: "Interviewer: 'How would you stop the same payment from being processed twice?'", cue: "면접관: '같은 결제가 두 번 처리되는 걸 어떻게 막을 거예요?' — 영어로 답해", model: "I'd give every payment request a client-generated idempotency key and store it with a unique constraint in the database. The first request does the work and records the key in the same transaction; any retry with that key hits the constraint and just returns the original result instead of charging again. So even if the client retries or the message gets redelivered, the money only moves once. It's the same shape as a ledger entry — you write the effect exactly once and key it so duplicates are impossible.", note: "핵심: idempotency key + unique constraint + 같은 트랜잭션에 기록. 'the money only moves once'가 결론.", concepts: ["idempotency", "double-processing", "unique-constraint", "payments"] },
  { key: "iv:scn:optimistic-vs-pessimistic", group: "scenario", sub: "interview", title: "Interviewer: 'Optimistic or pessimistic locking here — and why?'", cue: "면접관: '여기서 낙관적 락 vs 비관적 락, 뭘 쓰고 왜?' — 영어로 답해", model: "It depends on how much contention I actually expect on a single row. If conflicts are rare, I'd go optimistic — a version column, and I retry on the rare conflict. That keeps the happy path fast and doesn't hold locks. But if a lot of writers hammer the same hot row, like one popular listing, optimistic just turns into a retry storm, so I'd take a pessimistic row lock and serialize them. So my default is optimistic, and I only switch to pessimistic once I've measured real contention on a hot key.", note: "결정 기준은 'contention 측정'. retry storm 언급이 senior스러움.", concepts: ["optimistic-locking", "pessimistic-locking", "contention", "version-column"] },
  { key: "iv:scn:make-operation-idempotent", group: "scenario", sub: "interview", title: "Interviewer: 'This API mutates inventory. Make it idempotent.'", cue: "면접관: '이 API가 재고를 변경해요. 멱등하게 만들어 봐요.' — 영어로 답해", model: "The trick is to separate the request identity from the side effect. I'd attach a request ID to each call and keep a table of request IDs I've already applied, along with the resulting state. When a call comes in, I check that table inside the transaction: if I've seen the ID, I return the stored result and skip the mutation; if not, I apply the change and record the ID atomically. The important part is that the dedup record and the inventory write commit together — if they can split, you've just moved the bug.", note: "'dedup record and the write commit together' — 부분 적용 막는 게 포인트.", concepts: ["idempotency", "dedup-table", "atomic-commit", "inventory"] },
  { key: "iv:scn:source-of-truth-multi-node", group: "scenario", sub: "interview", title: "Interviewer: 'Across these services, where does the source of truth live?'", cue: "면접관: '이 여러 서비스들 중에서 진실의 원천은 어디에 둘 거예요?' — 영어로 답해", model: "I'd pick exactly one system of record per fact and make everything else a derived, read-only copy. For money and ownership, that's the ledger — it's append-only and authoritative, and it never gets edited in place. The other nodes can hold caches or projections for speed, but when they disagree, the ledger wins and they get rebuilt from it. The failure mode I see most is two services both thinking they own the same number, so the first decision I make is naming the single owner.", note: "'one system of record per fact', '두 서비스가 같은 숫자를 소유한다고 믿는 것'이 최악 케이스.", concepts: ["source-of-truth", "system-of-record", "ledger", "derived-data"] },
  { key: "iv:scn:reconcile-inventory-vs-ledger", group: "scenario", sub: "interview", title: "Interviewer: 'Inventory says 10, the ledger says 9. Walk me through how you reconcile.'", cue: "면접관: '재고는 10인데 원장은 9예요. 어떻게 맞출 건지 설명해 봐요.' — 영어로 답해", model: "I treat the ledger as authoritative — it's append-only and every change is traceable — and I treat the inventory count as the thing that drifted. I'd run a reconciliation job that replays the ledger entries for that item over the window and compares the expected balance to the live count, so I find the exact entry where they split. Usually it's a write that landed in one place but not the other — a partial failure or a missed event. The fix is to correct inventory from the ledger, never the reverse, and then close the gap that let them diverge. That's basically my whole career — making the physical count match the recorded numbers.", note: "마지막 문장이 Opendoor 내러티브 연결. ledger가 authoritative.", concepts: ["reconciliation", "ledger", "drift", "replay", "data-correctness"] },
  { key: "iv:scn:retry-and-dlq", group: "scenario", sub: "interview", title: "Interviewer: 'A message keeps failing. How do you handle retries and the dead-letter queue?'", cue: "면접관: '메시지가 계속 실패해요. 재시도랑 DLQ를 어떻게 처리할 거예요?' — 영어로 답해", model: "I'd retry with backoff a bounded number of times, because a lot of failures are transient — a brief timeout or a deadlock. But the consumer has to be idempotent first, or the retries themselves corrupt the data. Once the retry budget is exhausted, the message goes to a DLQ with enough context to know why it failed, and that fires an alert instead of silently disappearing. Then someone fixes the root cause and replays it. The thing I never do is drop a failed money or inventory message — it sits in the DLQ until it's resolved.", note: "'consumer idempotent first' 순서가 중요. 'never silently drop'.", concepts: ["retry", "backoff", "dead-letter-queue", "idempotency", "alerting"] },
  { key: "iv:scn:at-least-once-delivery", group: "scenario", sub: "interview", title: "Interviewer: 'Your queue is at-least-once. Design the consumer for that.'", cue: "면접관: '큐가 at-least-once예요. 그 전제로 컨슈머를 설계해 봐요.' — 영어로 답해", model: "At-least-once means I will see duplicates, full stop, so I design the consumer to make duplicates harmless instead of trying to make delivery exactly-once. Each message carries a stable ID, and the consumer checks a processed-IDs table before applying the effect, then records the ID in the same transaction as the work. So the second copy is a no-op that returns the same result. I'd rather have at-least-once delivery plus an idempotent consumer than chase exactly-once at the broker — that's where the simpler, more correct design lives.", note: "'make duplicates harmless, not delivery exactly-once'가 핵심 senior 통찰.", concepts: ["at-least-once", "exactly-once", "dedup", "idempotent-consumer"] },
  { key: "iv:scn:isolation-level-choice", group: "scenario", sub: "interview", title: "Interviewer: 'What isolation level would you run this transaction at?'", cue: "면접관: '이 트랜잭션은 어떤 격리 수준으로 돌릴 거예요?' — 영어로 답해", model: "For most reads I'm fine with read committed, but anything that reads a balance and then writes based on it needs more, because read committed lets the value change underneath me. For the money path I'd either bump it to serializable and retry on the occasional serialization failure, or use an explicit row lock or a version check to make the read-modify-write safe. It's really about which anomalies I can tolerate — for a financial balance the answer is none, so I pay for the stronger guarantee only on those statements, not globally.", note: "read-modify-write가 위험. 'pay for the guarantee only where needed'가 균형 잡힌 답.", concepts: ["isolation-level", "serializable", "read-committed", "read-modify-write"] },
  { key: "iv:scn:verify-correctness", group: "scenario", sub: "interview", title: "Interviewer: 'How would you actually verify this stays correct in production?'", cue: "면접관: '이게 운영에서 계속 맞다는 걸 실제로 어떻게 검증할 거예요?' — 영어로 답해", model: "I don't trust correctness I can't observe, so I'd run a continuous check that recomputes the totals from the ledger and compares them to the live state on a schedule. If the two ever disagree, it alerts before a customer notices. On top of that I'd assert invariants at write time — things like a balance never going negative — so bad states fail fast instead of leaking downstream. The whole point is that correctness is something I monitor, not something I assume held because the tests passed once.", note: "'correctness is something I monitor, not assume' — 그의 data-correctness 정체성 직격.", concepts: ["verification", "invariants", "reconciliation-job", "monitoring", "data-correctness"] },
  { key: "iv:scn:walk-me-through-tradeoff", group: "scenario", sub: "interview", title: "Interviewer: 'Strong consistency or availability for the inventory count — walk me through the trade-off.'", cue: "면접관: '재고 카운트에 강한 일관성 vs 가용성, 그 트레이드오프를 설명해 봐요.' — 영어로 답해", model: "I'd split it by what the number is doing. For displaying a count on a page, I'll take availability and accept it being a little stale — a slightly old number is fine and the page stays up. But at the moment we commit a transaction against that inventory, I need strong consistency, because selling the same unit twice is a real correctness failure, not a cosmetic one. So it's not one global choice — it's eventual consistency on the read path and a strongly consistent check at the point of commit. You only pay for strong consistency where being wrong actually costs money.", note: "분리해서 답하는 게 핵심: read는 가용성, commit은 강일관성. 'where being wrong costs money'.", concepts: ["consistency-vs-availability", "CAP", "eventual-consistency", "trade-off"] },
  { key: "iv:scn:defend-db-unique-constraint", group: "scenario", sub: "pair", title: "Teammate: \"Why put a unique constraint in the DB? Can't we just check in the app?\"", cue: "동료가 \"DB에 유니크 제약을 왜 걸어? 그냥 앱에서 체크하면 되잖아\"라고 함 — 영어로 답해", model: "We can do the app check too, but it's not enough on its own. Two requests can both pass the check at the same time and then both insert, so you still get a duplicate. The DB constraint is the only thing that's actually atomic here, so I'd keep that as the real guarantee and treat the app check as a fast pre-filter for nicer error messages.", note: "핵심: app check는 race condition을 못 막는다 → DB가 진짜 보증", concepts: ["unique-constraint", "race-condition", "data-integrity", "defense-in-depth"] },
  { key: "iv:scn:inmemory-check-fails-multinode", group: "scenario", sub: "pair", title: "Explaining why the in-memory dedup check breaks once you scale out", cue: "인메모리로 중복 체크하는 코드를 보고, 노드가 여러 대로 늘어나면 왜 깨지는지 설명해 — 영어로 답해", model: "The in-memory map works fine on one box, but the moment we run two instances each one has its own copy. So a request hits node A, another hits node B, neither sees the other, and both go through. Once we scale out, the only shared source of truth is the database or something like Redis. In-process state just doesn't hold across nodes.", note: "in-process state는 노드 간 공유가 안 된다는 게 핵심", concepts: ["distributed-systems", "shared-state", "horizontal-scaling", "deduplication"] },
  { key: "iv:scn:propose-idempotency-key", group: "scenario", sub: "pair", title: "Proposing an idempotency key for the payment / write endpoint", cue: "결제 같은 쓰기 엔드포인트에 멱등성 키를 넣자고 제안해봐 — 영어로 답해", model: "For this endpoint I'd add an idempotency key that the client sends with each request. We store it, and if the same key comes in again we just return the original result instead of doing the work twice. That way a retry after a timeout can't double-charge or double-post to the ledger. Small change, but it makes the whole thing safe to retry, which is exactly what you want for money movement.", note: "retry-safe → double-charge 방지. 재무 트랜잭션 맥락", concepts: ["idempotency", "retries", "financial-transactions", "api-design"] },
  { key: "iv:scn:suggest-audit-log-source-of-truth", group: "scenario", sub: "pair", title: "Suggesting an append-only audit log as the source of truth", cue: "상태를 직접 덮어쓰지 말고, append-only 감사 로그를 진실의 원천으로 두자고 제안해 — 영어로 답해", model: "Instead of mutating the row in place, I'd rather write an append-only log of every state change and derive the current state from that. When the numbers don't match later, we can replay exactly what happened and see where it went wrong. In my experience that's the difference between guessing and actually proving what the system did. It's saved me more than once on reconciliation.", note: "append-only ledger → 재현 가능 + 진실의 원천. 그의 강점 영역", concepts: ["audit-log", "event-sourcing", "source-of-truth", "auditability"] },
  { key: "iv:scn:pushback-premature-optimization", group: "scenario", sub: "pair", title: "Pushing back on premature optimization: \"let's measure first\"", cue: "동료가 미리부터 캐시랑 최적화를 넣자고 함. \"일단 측정부터 하자\"고 정중하게 막아봐 — 영어로 답해", model: "I get the instinct, but I'd hold off on the cache for now. We don't actually know this is the slow part yet, and a cache brings its own correctness problems, like stale data. Let's put a quick timing on it first and see where the real cost is. If it turns out this is the bottleneck, I'm all for it, but let's measure before we add complexity.", note: "정중한 push-back + 캐시는 correctness 비용이 있다는 포인트", concepts: ["premature-optimization", "profiling", "caching-tradeoffs", "collaboration"] },
  { key: "iv:scn:ask-traceid-structured-log", group: "scenario", sub: "pair", title: "Asking to add a trace id + structured logging before debugging", cue: "버그를 바로 파기 전에, trace id랑 구조화된 로그부터 넣자고 제안해 — 영어로 답해", model: "Before we start poking at this, can we add a trace id that follows the request through and switch these over to structured logs? Right now we're kind of debugging blind. Once each request carries an id, I can grep one transaction end to end and actually see where the number diverges. It'll take five minutes and save us a lot of guessing.", note: "관측 가능성 먼저 → end-to-end로 한 트랜잭션 추적", concepts: ["observability", "trace-id", "structured-logging", "debugging"] },
  { key: "iv:scn:narrate-reconciliation-job", group: "scenario", sub: "pair", title: "Narrating how the reconciliation job works to a teammate", cue: "재고와 원장을 맞추는 reconciliation 잡이 어떻게 도는지 동료한테 설명해 — 영어로 답해", model: "So the job runs nightly. It pulls the actual inventory on one side and the ledger balance on the other, then diffs them key by key. Anything that doesn't match gets written to a discrepancy table with both values and a timestamp, and we alert if the gap is over a threshold. The point isn't to auto-fix it, it's to surface the mismatch early so a human can decide before it compounds.", note: "diff → discrepancy table → alert. auto-fix 안 하고 surface. 그의 핵심 도메인", concepts: ["reconciliation", "data-correctness", "batch-jobs", "alerting"] },
  { key: "iv:scn:disagree-politely-on-approach", group: "scenario", sub: "pair", title: "Disagreeing politely: teammate wants a soft delete flag, you want the event", cue: "동료는 그냥 deleted 플래그 하나 넣자고 하고, 너는 삭제 이벤트를 남기자는 입장. 정중하게 이견을 말해 — 영어로 답해", model: "That'd work, and it's simpler, so I see the appeal. My one worry is that a flag only tells us the current state, not when or why it changed. For data we have to reconcile later, I'd lean toward recording the delete as an event so we keep the history. But it's not a hill I'll die on. If you feel strongly, let's go with the flag and revisit if it bites us.", note: "동의 → 우려 → 제안 → 양보. 협업 톤이 핵심", concepts: ["disagree-and-commit", "soft-delete", "history-preservation", "collaboration"] },
  { key: "iv:scn:ask-for-small-hint", group: "scenario", sub: "pair", title: "Asking for a small hint when stuck in the pairing session", cue: "페어링 중에 막혔을 때, 자연스럽게 작은 힌트를 부탁해 — 영어로 답해", model: "Let me talk through where I am. I've got the dedup working at the DB level, but I'm not sure this is the cleanest way to surface the conflict back to the caller. Am I overthinking it, or is there a simpler pattern you'd reach for here? A small nudge would help.", note: "막혔을 때 — 현재 상태 요약 → 구체적 질문 → 힌트 요청. 당황하지 않는 톤", concepts: ["pairing", "asking-for-help", "communication", "thinking-out-loud"] },
  { key: "iv:scn:close-summarize-what-we-built", group: "scenario", sub: "pair", title: "Closing: summarizing what you two built and what's left", cue: "세션 끝에서 우리가 뭘 만들었고 뭐가 남았는지 정리해 — 영어로 답해", model: "Okay, so to wrap up: we put the unique constraint and the idempotency key in, so the write is safe to retry now. We also added a trace id so we can follow one transaction end to end. What's still open is the reconciliation alert and a couple of edge-case tests around concurrent writes. Want me to take the tests and you take the alert?", note: "마무리 — 한 것 / 남은 것 / 다음 분담. 깔끔하게", concepts: ["wrap-up", "summarizing", "next-steps", "collaboration"] },
];

/** Every flashcard-style speaking card (reflex/concept/frame/scenario — no code). */
export const INTERVIEW_CARDS: InterviewCard[] = [
  ...INTERVIEW_CONCEPTS,
  ...INTERVIEW_FRAMES,
  ...INTERVIEW_SCENARIOS,
];

// ── The code-explain deck: look at REAL Java → say the CORE in English → short model answer ──
export type CodeCategory = "ds" | "algo" | "pattern" | "method" | "design" | "backend";

export interface CodeCard {
  key: string; // SRS card key, e.g. "iv:cd:ds:hashmap-lookup-by-key"
  category: CodeCategory;
  title: string;
  code: string; // real, focused Java to explain
  answer: string; // the model explanation — 1-2 sentences, core only
  keyPoints: string[]; // 2-3 short things worth saying out loud
}

export const INTERVIEW_CODE_CARDS: CodeCard[] = [
  { key: "iv:cd:ds:hashmap-lookup-by-key", category: "ds", title: "HashMap: price by zip", code: "Map<String, BigDecimal> avgPriceByZip = new HashMap<>();\navgPriceByZip.put(\"94103\", new BigDecimal(\"1250000\"));\navgPriceByZip.put(\"73301\", new BigDecimal(\"480000\"));\n\nBigDecimal price = avgPriceByZip.get(\"94103\");\nboolean known = avgPriceByZip.containsKey(\"00000\");\nBigDecimal fallback = avgPriceByZip.getOrDefault(\"99999\", BigDecimal.ZERO);", answer: "A HashMap gives average O(1) put and get by key, backed by hashing. There's no ordering guarantee.", keyPoints: ["O(1) average lookup by key", "no ordering", "getOrDefault avoids null checks"] },
  { key: "iv:cd:ds:hashset-dedup-membership", category: "ds", title: "HashSet: dedup listing IDs", code: "Set<Long> seenListings = new HashSet<>();\n\nfor (Long id : incomingListingIds) {\n    if (!seenListings.add(id)) {\n        // add returns false -> already seen, skip duplicate\n        continue;\n    }\n    process(id);\n}", answer: "A HashSet stores unique elements with O(1) add and contains. I use add returning false to detect duplicates in one call.", keyPoints: ["O(1) membership test", "unique elements only", "add() returns false if present"] },
  { key: "iv:cd:ds:arraylist-indexed-access", category: "ds", title: "ArrayList: ordered offers", code: "List<Offer> offers = new ArrayList<>();\noffers.add(new Offer(\"A\", 500_000));\noffers.add(new Offer(\"B\", 525_000));\n\nOffer first = offers.get(0);          // O(1) random access\noffers.remove(0);                     // O(n) shift\noffers.sort(Comparator.comparingInt(Offer::amount));", answer: "An ArrayList is a growable array with O(1) indexed access and amortized O(1) append. Inserting or removing in the middle is O(n) because elements shift.", keyPoints: ["O(1) random access by index", "amortized O(1) append", "O(n) middle insert/remove"] },
  { key: "iv:cd:ds:arraydeque-stack-queue", category: "ds", title: "ArrayDeque: stack and queue", code: "Deque<String> stack = new ArrayDeque<>();\nstack.push(\"a\");           // add to head\nstack.push(\"b\");\nString top = stack.pop();  // \"b\" -> LIFO\n\nDeque<String> queue = new ArrayDeque<>();\nqueue.offer(\"x\");          // add to tail\nString next = queue.poll(); // \"x\" -> FIFO", answer: "ArrayDeque is a double-ended queue with O(1) at both ends: push/pop give a LIFO stack, offer/poll give a FIFO queue. It's the preferred choice over Stack or LinkedList.", keyPoints: ["O(1) at both ends", "stack via push/pop, queue via offer/poll", "preferred over Stack/LinkedList"] },
  { key: "iv:cd:ds:priorityqueue-top-offers", category: "ds", title: "PriorityQueue: highest offer", code: "// max-heap by offer amount\nPriorityQueue<Offer> pq =\n    new PriorityQueue<>(Comparator.comparingInt(Offer::amount).reversed());\n\npq.offer(new Offer(\"A\", 500_000));\npq.offer(new Offer(\"B\", 540_000));\n\nOffer best = pq.poll();   // B, 540_000 -> O(log n)", answer: "A PriorityQueue is a binary heap that pops the smallest element by its comparator, so I reverse the comparator for a max-heap. offer and poll are O(log n).", keyPoints: ["heap: min by default", "reversed comparator = max-heap", "O(log n) offer/poll, O(1) peek"] },
  { key: "iv:cd:ds:linkedhashmap-lru-cache", category: "ds", title: "LinkedHashMap: LRU cache", code: "Map<Long, Home> cache = new LinkedHashMap<>(16, 0.75f, true) {\n    @Override\n    protected boolean removeEldestEntry(Map.Entry<Long, Home> e) {\n        return size() > 100;   // evict oldest when over capacity\n    }\n};\ncache.get(42L);  // access-order=true moves 42 to most-recent", answer: "LinkedHashMap keeps entries in insertion or access order via a linked list. With access-order plus removeEldestEntry, that gives a simple LRU cache.", keyPoints: ["predictable iteration order", "access-order flag for LRU", "removeEldestEntry caps size"] },
  { key: "iv:cd:ds:treemap-sorted-range", category: "ds", title: "TreeMap: price range query", code: "TreeMap<Integer, Home> byPrice = new TreeMap<>();\nbyPrice.put(450_000, homeA);\nbyPrice.put(600_000, homeB);\nbyPrice.put(800_000, homeC);\n\n// homes priced 500k..700k inclusive\nSortedMap<Integer, Home> mid = byPrice.subMap(500_000, true, 700_000, true);\nInteger justBelow = byPrice.floorKey(650_000); // 600_000", answer: "A TreeMap is a sorted map backed by a red-black tree with O(log n) operations. That unlocks range queries and floor/ceiling lookups a HashMap can't do.", keyPoints: ["sorted keys, O(log n)", "range queries via subMap", "floorKey/ceilingKey navigation"] },
  { key: "iv:cd:ds:trie-node-prefix", category: "ds", title: "Trie node: address prefix", code: "class TrieNode {\n    Map<Character, TrieNode> children = new HashMap<>();\n    boolean isWord;\n}\n\nvoid insert(TrieNode root, String word) {\n    TrieNode cur = root;\n    for (char c : word.toCharArray()) {\n        cur = cur.children.computeIfAbsent(c, k -> new TrieNode());\n    }\n    cur.isWord = true;\n}", answer: "A trie stores strings character by character along a path, so prefix lookups run in O(length) no matter how many words are stored. That's what makes it ideal for autocomplete.", keyPoints: ["O(word length) insert/search", "shared prefixes save space", "great for autocomplete"] },
  { key: "iv:cd:ds:adjacency-list-graph", category: "ds", title: "Adjacency list: BFS graph", code: "Map<Integer, List<Integer>> adj = new HashMap<>();\nvoid addEdge(int u, int v) {\n    adj.computeIfAbsent(u, k -> new ArrayList<>()).add(v);\n    adj.computeIfAbsent(v, k -> new ArrayList<>()).add(u);\n}\n\n// neighbors of node u\nList<Integer> neighbors = adj.getOrDefault(u, List.of());", answer: "An adjacency list maps each node to its neighbor list, storing only real edges in O(V+E) space. It's the default for sparse graphs, where a matrix would waste space.", keyPoints: ["O(V+E) space for sparse graphs", "fast neighbor iteration", "computeIfAbsent builds lists lazily"] },
  { key: "iv:cd:ds:map-merge-counting", category: "ds", title: "Map.merge: count offers", code: "Map<String, Integer> offersPerZip = new HashMap<>();\n\nfor (Offer o : offers) {\n    offersPerZip.merge(o.zip(), 1, Integer::sum);\n}\n// merge: if absent put 1, else apply sum(old, 1)\nint count94103 = offersPerZip.getOrDefault(\"94103\", 0);", answer: "Map.merge handles absent-versus-present in one line: it inserts the value if the key is missing, otherwise applies the remap function. It's the clean idiom for frequency counting.", keyPoints: ["one-line frequency count", "inserts if absent, else remaps", "replaces get-then-put"] },
  { key: "iv:cd:algo:two-pointers-pair-sum", category: "algo", title: "Two pointers: pair sum", code: "// prices sorted ascending; find two offers summing to budget\nint lo = 0, hi = prices.length - 1;\nwhile (lo < hi) {\n    int sum = prices[lo] + prices[hi];\n    if (sum == budget) return new int[]{lo, hi};\n    if (sum < budget) lo++;   // need bigger -> move left up\n    else hi--;                // too big   -> move right down\n}\nreturn new int[]{-1, -1};", answer: "On a sorted array, two pointers converge from both ends, moving whichever shifts the sum toward the target. O(n) time, O(1) space.", keyPoints: ["array must be sorted", "converge from both ends", "O(n) time, O(1) space"] },
  { key: "iv:cd:algo:sliding-window-max-sum", category: "algo", title: "Sliding window: max sum", code: "// max revenue over any k consecutive days\nint sum = 0, best;\nfor (int i = 0; i < k; i++) sum += sales[i];\nbest = sum;\nfor (int i = k; i < sales.length; i++) {\n    sum += sales[i] - sales[i - k]; // add new, drop oldest\n    best = Math.max(best, sum);\n}\nreturn best;", answer: "Keep a running sum of a fixed window, sliding it by adding the entering element and subtracting the leaving one. That reuse makes it O(n) instead of O(n*k).", keyPoints: ["reuse the running sum", "add new, drop oldest", "O(n) not O(n*k)"] },
  { key: "iv:cd:algo:binary-search-lower-bound", category: "algo", title: "Binary search: lower bound", code: "// first index with price >= target\nint lo = 0, hi = prices.length; // hi exclusive\nwhile (lo < hi) {\n    int mid = lo + (hi - lo) / 2; // avoids overflow\n    if (prices[mid] < target) lo = mid + 1;\n    else hi = mid;\n}\nreturn lo; // insertion point", answer: "Halve a sorted range each step to find the first element not less than the target. O(log n), and the half-open interval keeps it off-by-one-safe.", keyPoints: ["sorted input required", "half-open interval [lo,hi)", "O(log n)"] },
  { key: "iv:cd:algo:bfs-shortest-hops", category: "algo", title: "BFS: shortest hops", code: "Queue<Integer> q = new ArrayDeque<>();\nboolean[] seen = new boolean[n];\nq.add(start); seen[start] = true;\nint dist = 0;\nwhile (!q.isEmpty()) {\n    for (int sz = q.size(); sz > 0; sz--) { // one level\n        int node = q.poll();\n        if (node == target) return dist;\n        for (int nb : adj.get(node))\n            if (!seen[nb]) { seen[nb] = true; q.add(nb); }\n    }\n    dist++;\n}\nreturn -1;", answer: "BFS explores a graph level by level with a queue, so the first time you reach a node is the shortest hop count. Mark seen on enqueue; O(V+E).", keyPoints: ["queue = level order", "mark seen on enqueue", "first reach = shortest path"] },
  { key: "iv:cd:algo:dfs-recursion-count", category: "algo", title: "DFS: count region", code: "// size of connected region of 'owned' cells\nint dfs(int[][] grid, int r, int c) {\n    if (r < 0 || c < 0 || r >= grid.length || c >= grid[0].length\n            || grid[r][c] != 1) return 0;\n    grid[r][c] = 0; // mark visited in place\n    return 1 + dfs(grid, r+1, c) + dfs(grid, r-1, c)\n             + dfs(grid, r, c+1) + dfs(grid, r, c-1);\n}", answer: "DFS floods a grid region by recursing into all four neighbors and marking cells visited in place. The base case guards bounds and non-matching cells; O(cells).", keyPoints: ["recurse into 4 neighbors", "mark visited in place", "base case guards bounds"] },
  { key: "iv:cd:algo:backtracking-subsets", category: "algo", title: "Backtracking: subsets", code: "void build(int[] nums, int start, List<Integer> cur, List<List<Integer>> out) {\n    out.add(new ArrayList<>(cur));      // record current choice\n    for (int i = start; i < nums.length; i++) {\n        cur.add(nums[i]);               // choose\n        build(nums, i + 1, cur, out);   // explore\n        cur.remove(cur.size() - 1);     // un-choose (backtrack)\n    }\n}", answer: "Backtracking builds candidates with a choose / explore / un-choose loop, undoing each pick to try the next. The start index avoids duplicate subsets; O(2^n).", keyPoints: ["choose-explore-unchoose", "start index avoids dups", "O(2^n) subsets"] },
  { key: "iv:cd:algo:memoized-dp-fib-style", category: "algo", title: "Memoized DP: stairs", code: "// ways to climb n steps taking 1 or 2 at a time\nint climb(int n, Integer[] memo) {\n    if (n <= 2) return n;\n    if (memo[n] != null) return memo[n]; // reuse subproblem\n    return memo[n] = climb(n-1, memo) + climb(n-2, memo);\n}", answer: "Top-down DP caches each subproblem's answer so overlapping calls compute once. That collapses exponential recursion to O(n) time and space.", keyPoints: ["cache overlapping subproblems", "compute each state once", "exponential -> O(n)"] },
  { key: "iv:cd:algo:greedy-activity-pick", category: "algo", title: "Greedy: max bookings", code: "// max non-overlapping showings; sort by end time\nArrays.sort(showings, (a, b) -> a[1] - b[1]);\nint count = 0, end = Integer.MIN_VALUE;\nfor (int[] s : showings) {\n    if (s[0] >= end) {   // starts after last chosen ends\n        count++;\n        end = s[1];      // greedily take earliest finisher\n    }\n}\nreturn count;", answer: "Sort by end time and always take the earliest-finishing compatible interval — that local choice is provably globally optimal here. Sorting dominates at O(n log n).", keyPoints: ["sort by end time", "earliest finish wins", "local pick = global optimum"] },
  { key: "iv:cd:algo:merge-intervals", category: "algo", title: "Merge intervals", code: "Arrays.sort(intervals, (a, b) -> a[0] - b[0]); // by start\nList<int[]> merged = new ArrayList<>();\nfor (int[] cur : intervals) {\n    int[] last = merged.isEmpty() ? null : merged.get(merged.size()-1);\n    if (last != null && cur[0] <= last[1])\n        last[1] = Math.max(last[1], cur[1]); // overlap -> extend\n    else\n        merged.add(cur);                     // gap -> new block\n}\nreturn merged.toArray(new int[0][]);", answer: "Sort by start, then sweep once: extend the last interval when the next overlaps, otherwise start a new block. Sorting makes it O(n log n).", keyPoints: ["sort by start first", "overlap -> extend end", "O(n log n) from sort"] },
  { key: "iv:cd:algo:top-k-min-heap", category: "algo", title: "Top-K with min-heap", code: "// k highest-priced listings\nPriorityQueue<Integer> heap = new PriorityQueue<>(); // min-heap\nfor (int price : prices) {\n    heap.offer(price);\n    if (heap.size() > k) heap.poll(); // drop smallest\n}\nreturn new ArrayList<>(heap); // the k largest", answer: "Keep a size-k min-heap so the smallest of the current top-k sits at the root and gets evicted when something bigger arrives. O(n log k), beating a full O(n log n) sort.", keyPoints: ["min-heap of size k", "root = smallest survivor", "O(n log k) beats full sort"] },
  { key: "iv:cd:pattern:strategy-pattern", category: "pattern", title: "Strategy: swap the algorithm", code: "interface PricingStrategy {\n    Money price(Home home);\n}\n\nclass MarketPricing implements PricingStrategy {\n    public Money price(Home home) { return comps(home); }\n}\n\nclass QuickOfferPricing implements PricingStrategy {\n    public Money price(Home home) { return comps(home).times(0.95); }\n}\n\nclass OfferEngine {\n    private final PricingStrategy strategy;\n    OfferEngine(PricingStrategy s) { this.strategy = s; }\n    Money makeOffer(Home home) { return strategy.price(home); }\n}", answer: "Strategy lets you swap the pricing algorithm at runtime without touching the caller. The engine just holds a PricingStrategy and delegates, so a new pricing model is a new class.", keyPoints: ["Swap algorithm via interface", "No change to caller", "New behavior = new class"] },
  { key: "iv:cd:pattern:factory-pattern", category: "pattern", title: "Factory: centralize creation", code: "interface Offer { Money amount(); }\n\nclass OfferFactory {\n    static Offer create(OfferType type, Home home) {\n        return switch (type) {\n            case INSTANT  -> new InstantOffer(home);\n            case LISTED   -> new ListedOffer(home);\n            case TRADE_IN -> new TradeInOffer(home);\n        };\n    }\n}\n\n// caller: Offer o = OfferFactory.create(INSTANT, home);", answer: "A Factory centralizes object creation behind one method, so callers ask for an Offer by type and never depend on the concrete classes or their constructors.", keyPoints: ["Hides concrete classes", "One place to create", "Caller depends on interface"] },
  { key: "iv:cd:pattern:singleton-pattern", category: "pattern", title: "Singleton: one shared instance", code: "enum PricingConfig {\n    INSTANCE;\n\n    private final Map<String, Double> rates = loadRates();\n\n    double marketRate(String zip) {\n        return rates.getOrDefault(zip, 1.0);\n    }\n}\n\n// usage: PricingConfig.INSTANCE.marketRate(\"94107\");", answer: "Singleton guarantees exactly one shared instance with a global access point. Using an enum gives you that for free, thread-safe, with no manual locking.", keyPoints: ["Exactly one instance", "Enum = thread-safe", "Global access point"] },
  { key: "iv:cd:pattern:observer-pattern", category: "pattern", title: "Observer: notify subscribers", code: "interface PriceListener {\n    void onPriceChange(Home home, Money newPrice);\n}\n\nclass Listing {\n    private final List<PriceListener> listeners = new ArrayList<>();\n    void subscribe(PriceListener l) { listeners.add(l); }\n\n    void setPrice(Home home, Money price) {\n        listeners.forEach(l -> l.onPriceChange(home, price));\n    }\n}\n// EmailAlert and SearchIndex implement PriceListener", answer: "Observer lets a subject broadcast changes to many subscribers without knowing who they are. When a price changes, every registered listener gets called.", keyPoints: ["One-to-many notification", "Publisher decoupled from subscribers", "Subscribe/unsubscribe at runtime"] },
  { key: "iv:cd:pattern:builder-pattern", category: "pattern", title: "Builder: step-by-step construction", code: "class Home {\n    private int beds, baths;\n    private String zip;\n    private Home() {}\n\n    static class Builder {\n        private final Home h = new Home();\n        Builder beds(int n)   { h.beds = n;  return this; }\n        Builder baths(int n)  { h.baths = n; return this; }\n        Builder zip(String z) { h.zip = z;   return this; }\n        Home build()          { return h; }\n    }\n}\n// new Home.Builder().beds(3).baths(2).zip(\"94107\").build();", answer: "Builder constructs an object step by step with a fluent, readable chain. It replaces a telescoping constructor of optional params and keeps the object immutable.", keyPoints: ["Fluent readable construction", "Avoids telescoping constructors", "Good for optional params"] },
  { key: "iv:cd:pattern:adapter-pattern", category: "pattern", title: "Adapter: bridge incompatible APIs", code: "interface PaymentGateway {\n    void charge(Money amount, String account);\n}\n\n// third-party class we can't change\nclass StripeClient {\n    void createCharge(long cents, String token) { /* ... */ }\n}\n\nclass StripeAdapter implements PaymentGateway {\n    private final StripeClient stripe;\n    StripeAdapter(StripeClient s) { this.stripe = s; }\n    public void charge(Money amount, String account) {\n        stripe.createCharge(amount.toCents(), account);\n    }\n}", answer: "Adapter wraps a third-party class to fit your own interface, so the rest of the code talks to PaymentGateway and never sees Stripe's incompatible API.", keyPoints: ["Wraps incompatible interface", "Isolates third-party API", "Caller sees your interface"] },
  { key: "iv:cd:pattern:template-method-pattern", category: "pattern", title: "Template Method: fixed skeleton", code: "abstract class OfferPipeline {\n    final Offer run(Home home) {\n        Comps data = fetchComps(home);    // shared\n        Money price = computePrice(data); // varies\n        return toOffer(price);            // shared\n    }\n    abstract Money computePrice(Comps data);\n    abstract Comps fetchComps(Home home);\n    abstract Offer toOffer(Money price);\n}\n\nclass InstantPipeline extends OfferPipeline {\n    Money computePrice(Comps data) { return data.median().times(0.97); }\n    // fetchComps, toOffer inherited skeleton steps\n}", answer: "Template Method fixes the overall algorithm skeleton in a final base method and lets subclasses override only the steps that vary. The run() order is locked; only the steps change.", keyPoints: ["Skeleton in base class", "Subclasses fill in steps", "Algorithm order is fixed"] },
  { key: "iv:cd:pattern:dependency-injection", category: "pattern", title: "Dependency Injection: pass collaborators in", code: "class OfferService {\n    private final PricingStrategy pricing;\n    private final PaymentGateway payments;\n\n    // dependencies injected, not constructed inside\n    OfferService(PricingStrategy pricing, PaymentGateway payments) {\n        this.pricing = pricing;\n        this.payments = payments;\n    }\n}\n// wiring: new OfferService(new MarketPricing(), new StripeAdapter(stripe));", answer: "Dependency Injection passes a class's collaborators in through the constructor instead of newing them inside. That decouples it from concrete implementations and makes it trivial to mock in tests.", keyPoints: ["Dependencies passed in, not created", "Decouples from concretes", "Easy to mock/test"] },
  { key: "iv:cd:method:dedup-with-hashset", category: "method", title: "Dedup with HashSet", code: "List<String> dedupZipCodes(List<String> zips) {\n    Set<String> seen = new HashSet<>();\n    List<String> result = new ArrayList<>();\n    for (String zip : zips) {\n        if (seen.add(zip)) {   // add() returns false if already present\n            result.add(zip);\n        }\n    }\n    return result;\n}", answer: "Removes duplicates while keeping first-seen order, using that HashSet.add returns false if the element was already there. One O(1) call both tests and records membership.", keyPoints: ["add() returns false if present", "O(1) membership check", "keeps insertion order"] },
  { key: "iv:cd:method:idempotency-key-check", category: "method", title: "Idempotency key guard", code: "Offer createOffer(OfferRequest req, String idempotencyKey) {\n    Optional<Offer> existing = offerRepo.findByIdempotencyKey(idempotencyKey);\n    if (existing.isPresent()) {\n        return existing.get();          // replay: return prior result\n    }\n    Offer offer = offerRepo.save(req.toOffer(idempotencyKey));\n    return offer;\n}", answer: "Makes offer creation safe to retry: if the idempotency key was already used, it returns the original offer instead of writing a duplicate.", keyPoints: ["dedupe writes on retry", "lookup key before insert", "return prior result on replay"] },
  { key: "iv:cd:method:retry-with-backoff", category: "method", title: "Retry with backoff", code: "<T> T retry(Supplier<T> op, int maxAttempts) throws InterruptedException {\n    long delay = 100;\n    for (int attempt = 1; ; attempt++) {\n        try {\n            return op.get();\n        } catch (TransientException e) {\n            if (attempt >= maxAttempts) throw e;\n            Thread.sleep(delay);\n            delay *= 2;             // exponential backoff\n        }\n    }\n}", answer: "Retries a flaky call up to a limit, doubling the wait each time. It only retries transient errors and rethrows once attempts run out.", keyPoints: ["only retry transient errors", "delay doubles each attempt", "rethrow after max attempts"] },
  { key: "iv:cd:method:lru-get-linkedhashmap", category: "method", title: "LRU cache via LinkedHashMap", code: "class LruCache<K, V> extends LinkedHashMap<K, V> {\n    private final int capacity;\n    LruCache(int capacity) {\n        super(capacity, 0.75f, true);   // true = access-order\n        this.capacity = capacity;\n    }\n    @Override\n    protected boolean removeEldestEntry(Map.Entry<K, V> eldest) {\n        return size() > capacity;       // evict when over capacity\n    }\n}", answer: "An LRU cache built on LinkedHashMap in access-order mode, so a get moves the entry to the back. Overriding removeEldestEntry evicts the oldest key once we exceed capacity.", keyPoints: ["access-order constructor flag", "get reorders entry", "removeEldestEntry evicts LRU"] },
  { key: "iv:cd:method:reconcile-maps-diff", category: "method", title: "Reconcile two maps into a diff", code: "Map<String, BigDecimal> priceDeltas(Map<String, BigDecimal> oldP,\n                                   Map<String, BigDecimal> newP) {\n    Map<String, BigDecimal> deltas = new HashMap<>();\n    Set<String> ids = new HashSet<>(oldP.keySet());\n    ids.addAll(newP.keySet());\n    for (String id : ids) {\n        BigDecimal a = oldP.getOrDefault(id, BigDecimal.ZERO);\n        BigDecimal b = newP.getOrDefault(id, BigDecimal.ZERO);\n        if (a.compareTo(b) != 0) deltas.put(id, b.subtract(a));\n    }\n    return deltas;\n}", answer: "Diffs old vs new prices into a map of changes. It unions both key sets so added and removed homes are caught, and only keeps entries that actually changed.", keyPoints: ["union both key sets", "getOrDefault for missing side", "only emit changed entries"] },
  { key: "iv:cd:method:upsert", category: "method", title: "Upsert (insert or update)", code: "void upsertInventory(String homeId, int count) {\n    InventoryRow row = repo.findById(homeId).orElse(null);\n    if (row == null) {\n        repo.save(new InventoryRow(homeId, count));   // insert\n    } else {\n        row.setCount(count);\n        repo.save(row);                               // update\n    }\n}", answer: "Inserts the inventory row if it's missing, otherwise updates the existing one. The presence check on the key decides between create and update.", keyPoints: ["lookup by key first", "insert if absent, update if present", "one logical write either way"] },
  { key: "iv:cd:method:count-with-map-merge", category: "method", title: "Count with Map.merge", code: "Map<String, Integer> countByCity(List<Home> homes) {\n    Map<String, Integer> counts = new HashMap<>();\n    for (Home h : homes) {\n        counts.merge(h.getCity(), 1, Integer::sum);\n    }\n    return counts;\n}", answer: "Builds a frequency map of homes per city. merge inserts 1 the first time and otherwise sums into the existing count, so there's no null check.", keyPoints: ["merge handles first vs. existing", "no null/contains check", "Integer::sum combines counts"] },
  { key: "iv:cd:method:validate-state-transition", category: "method", title: "Validate a state transition", code: "private static final Map<Status, Set<Status>> ALLOWED = Map.of(\n    Status.DRAFT,    Set.of(Status.SENT),\n    Status.SENT,     Set.of(Status.ACCEPTED, Status.REJECTED),\n    Status.ACCEPTED, Set.of(Status.CLOSED));\n\nvoid transition(Offer offer, Status next) {\n    Set<Status> ok = ALLOWED.getOrDefault(offer.getStatus(), Set.of());\n    if (!ok.contains(next)) {\n        throw new IllegalStateException(offer.getStatus() + \" -> \" + next);\n    }\n    offer.setStatus(next);\n}", answer: "Guards an offer's lifecycle by checking a move against an allowed-edges map before applying it. Anything not in the map throws, so illegal jumps like DRAFT to CLOSED can't happen.", keyPoints: ["allowed transitions as a map", "reject anything not listed", "throw on illegal jump"] },
  { key: "iv:cd:method:binary-search-sorted", category: "method", title: "Binary search a sorted list", code: "int firstHomeAtOrAbove(List<Integer> sortedPrices, int target) {\n    int lo = 0, hi = sortedPrices.size();   // half-open [lo, hi)\n    while (lo < hi) {\n        int mid = lo + (hi - lo) / 2;\n        if (sortedPrices.get(mid) < target) {\n            lo = mid + 1;\n        } else {\n            hi = mid;\n        }\n    }\n    return lo;   // insertion point\n}", answer: "A lower-bound binary search returning the first index whose price is at least the target, the insertion point. mid uses lo + (hi-lo)/2 to avoid overflow.", keyPoints: ["lower bound / insertion point", "O(log n)", "lo + (hi-lo)/2 avoids overflow"] },
  { key: "iv:cd:method:group-by-computeifabsent", category: "method", title: "Group-by with computeIfAbsent", code: "Map<String, List<Home>> groupByCity(List<Home> homes) {\n    Map<String, List<Home>> byCity = new HashMap<>();\n    for (Home h : homes) {\n        byCity.computeIfAbsent(h.getCity(), k -> new ArrayList<>())\n              .add(h);\n    }\n    return byCity;\n}", answer: "Groups homes into per-city lists. computeIfAbsent creates the list the first time a city appears and returns it, so we append in one expression.", keyPoints: ["lazily creates the list", "returns value to append to", "no contains/get-put dance"] },
  { key: "iv:cd:design:pricing-strategy", category: "design", title: "Pricing Strategy pattern", code: "interface PricingStrategy {\n    BigDecimal price(Home home);\n}\n\nclass CompsPricing implements PricingStrategy {\n    public BigDecimal price(Home home) { return medianOfComps(home); }\n}\n\nclass AvmPricing implements PricingStrategy {\n    public BigDecimal price(Home home) { return model.predict(home); }\n}\n\nclass OfferEngine {\n    private PricingStrategy strategy;\n    OfferEngine(PricingStrategy s) { this.strategy = s; }\n    BigDecimal makeOffer(Home home) { return strategy.price(home); }\n}", answer: "I model pricing with the Strategy pattern so the OfferEngine can swap algorithms — comps vs AVM model — at runtime without changing its own code.", keyPoints: ["Strategy = swap algorithm", "engine depends on interface", "open for new pricing rules"] },
  { key: "iv:cd:design:home-status-state-machine", category: "design", title: "Home status state machine", code: "enum HomeStatus {\n    LISTED, UNDER_OFFER, IN_ESCROW, SOLD, CANCELLED;\n\n    private static final Map<HomeStatus, Set<HomeStatus>> NEXT = Map.of(\n        LISTED,      Set.of(UNDER_OFFER, CANCELLED),\n        UNDER_OFFER, Set.of(IN_ESCROW, CANCELLED),\n        IN_ESCROW,   Set.of(SOLD, CANCELLED),\n        SOLD,        Set.of(),\n        CANCELLED,   Set.of());\n\n    boolean canMoveTo(HomeStatus next) {\n        return NEXT.get(this).contains(next);\n    }\n}", answer: "I model the home lifecycle as an enum state machine with an explicit allowed-transitions map, so illegal jumps like LISTED to SOLD are rejected in one guard.", keyPoints: ["enum + transition map", "reject illegal transitions", "single source of truth"] },
  { key: "iv:cd:design:inventory-ledger-reconciler", category: "design", title: "Inventory-ledger reconciler", code: "interface Reconciler {\n    List<Discrepancy> reconcile(List<Home> inventory, List<LedgerEntry> ledger);\n}\n\nclass InventoryReconciler implements Reconciler {\n    public List<Discrepancy> reconcile(List<Home> inv, List<LedgerEntry> led) {\n        Map<String, Home> byId = inv.stream()\n            .collect(toMap(Home::id, h -> h));\n        return led.stream()\n            .filter(e -> !matches(byId.get(e.homeId()), e))\n            .map(Discrepancy::of)\n            .toList();\n    }\n}", answer: "I reconcile inventory against the ledger by indexing homes into a map for O(1) lookup, then streaming the ledger to emit only the entries that don't match.", keyPoints: ["index to map = O(1) join", "emit discrepancies only", "two sources, one truth check"] },
  { key: "iv:cd:design:idempotent-payment-processor", category: "design", title: "Idempotent payment processor", code: "class PaymentProcessor {\n    private final Set<String> seen = ConcurrentHashMap.newKeySet();\n\n    Receipt charge(String idempotencyKey, Money amount) {\n        if (!seen.add(idempotencyKey)) {\n            return existingReceipt(idempotencyKey);   // replay, no double charge\n        }\n        Receipt r = gateway.charge(amount);\n        store(idempotencyKey, r);\n        return r;\n    }\n}", answer: "I make payments idempotent by keying each charge on a client-supplied idempotency key, so a retried request returns the original receipt instead of charging twice.", keyPoints: ["idempotency key dedupes", "retry-safe = no double charge", "atomic add then charge"] },
  { key: "iv:cd:design:status-change-observer", category: "design", title: "Status-change Observer", code: "interface StatusListener {\n    void onChange(Home home, HomeStatus from, HomeStatus to);\n}\n\nclass Home {\n    private final List<StatusListener> listeners = new ArrayList<>();\n    private HomeStatus status;\n\n    void addListener(StatusListener l) { listeners.add(l); }\n\n    void setStatus(HomeStatus next) {\n        HomeStatus prev = this.status;\n        this.status = next;\n        listeners.forEach(l -> l.onChange(this, prev, next));\n    }\n}", answer: "I broadcast status changes with the Observer pattern, so notifications, analytics, and escrow can subscribe independently without the Home knowing who reacts.", keyPoints: ["Observer = decouple reactions", "subscribers added at runtime", "Home doesn't know listeners"] },
  { key: "iv:cd:design:token-bucket-rate-limiter", category: "design", title: "Token-bucket rate limiter", code: "class TokenBucket {\n    private final long capacity;\n    private final double refillPerSec;\n    private double tokens;\n    private long lastNanos = System.nanoTime();\n\n    synchronized boolean tryAcquire() {\n        long now = System.nanoTime();\n        tokens = Math.min(capacity,\n            tokens + (now - lastNanos) / 1e9 * refillPerSec);\n        lastNanos = now;\n        if (tokens < 1) return false;\n        tokens -= 1;\n        return true;\n    }\n}", answer: "I rate-limit with a token bucket that refills lazily based on elapsed time, so it allows short bursts up to capacity while capping the steady rate.", keyPoints: ["lazy refill on elapsed time", "allows bursts up to capacity", "steady rate = refillPerSec"] },
  { key: "iv:cd:design:lru-valuation-cache", category: "design", title: "LRU valuation cache", code: "class ValuationCache extends LinkedHashMap<String, BigDecimal> {\n    private final int capacity;\n\n    ValuationCache(int capacity) {\n        super(16, 0.75f, true);          // access-order\n        this.capacity = capacity;\n    }\n\n    @Override\n    protected boolean removeEldestEntry(Map.Entry<String, BigDecimal> e) {\n        return size() > capacity;        // evict least-recently-used\n    }\n}", answer: "I cache home valuations with an access-ordered LinkedHashMap that evicts the least-recently-used entry, giving an LRU cache with O(1) get and put.", keyPoints: ["access-order LinkedHashMap", "removeEldestEntry = evict LRU", "O(1) get/put"] },
  { key: "iv:cd:design:append-only-audit-log", category: "design", title: "Append-only audit log", code: "record AuditEntry(Instant at, String actor, String action, String prevHash, String hash) {}\n\nclass AuditLog {\n    private final List<AuditEntry> entries = new ArrayList<>();\n\n    synchronized void append(String actor, String action) {\n        String prev = entries.isEmpty() ? \"GENESIS\"\n            : entries.get(entries.size() - 1).hash();\n        String hash = sha256(prev + actor + action);\n        entries.add(new AuditEntry(Instant.now(), actor, action, prev, hash));\n    }\n}", answer: "I model the audit trail as an append-only, hash-chained log where each entry hashes the previous one, so any tampering breaks the chain and is detectable.", keyPoints: ["append-only, no mutation", "hash chain = tamper-evident", "immutable records"] },
];

export const INTERVIEW_DECK_COUNTS = {
  reflex: REFLEX_CARDS.length,
  core: CORE_REFLEX.length,
  concept: INTERVIEW_CONCEPTS.length,
  frame: INTERVIEW_FRAMES.length,
  scenario: INTERVIEW_SCENARIOS.length,
  code: INTERVIEW_CODE_CARDS.length,
} as const;
