// YouTube id helpers shared by the clients.
//
// NOTE: a plain fetch() of YouTube's timedtext is NOT viable anymore — YouTube gates it behind a
// POToken generated by its BotGuard JS, so a raw request (even from a residential IP) returns an
// empty body. The mobile client therefore fetches transcripts inside a real browser (a hidden
// WebView, see mobile/src/lib/youtube-transcript-webview.tsx) where that JS actually runs.

export function extractYoutubeId(urlOrId: string): string | null {
  const s = urlOrId.trim();
  if (/^[a-zA-Z0-9_-]{11}$/.test(s)) return s;
  const patterns = [
    /[?&]v=([a-zA-Z0-9_-]{11})/,
    /youtu\.be\/([a-zA-Z0-9_-]{11})/,
    /\/shorts\/([a-zA-Z0-9_-]{11})/,
    /\/embed\/([a-zA-Z0-9_-]{11})/,
  ];
  for (const p of patterns) {
    const m = s.match(p);
    if (m) return m[1];
  }
  return null;
}
