import { useCallback, useRef, useState } from 'react';
import { WebView, type WebViewMessageEvent } from 'react-native-webview';
import { extractYoutubeId, type TranscriptSegment } from '@shadow-ai/core';

// On-device YouTube transcript fetch via a hidden WebView.
//
// Why a WebView and not a plain fetch(): YouTube now gates the timedtext endpoint behind a
// POToken generated by its BotGuard JS. A raw fetch (even from a residential IP) gets an empty
// body. A WebView is a REAL browser — it runs YouTube's own JS, so the session is "trusted" and
// the same-origin fetch of the caption track has a real shot at returning data. This is the
// on-device path that lets the phone import arbitrary URLs without a residential proxy.
//
// The injected script reads the caption track from ytInitialPlayerResponse, fetches json3 from
// inside the page, and posts {title, segments} (or {error: <reason>}) back to React Native.

export interface WebViewTranscriptResult {
  title: string;
  segments: TranscriptSegment[];
}

const TIMEOUT_MS = 25_000;

const INJECTED = `
(function () {
  function post(o) { window.ReactNativeWebView.postMessage(JSON.stringify(o)); }
  function grab() {
    try {
      var pr = window.ytInitialPlayerResponse;
      if (!pr) return post({ error: 'NO_PLAYER_RESPONSE' });
      var title = (pr.videoDetails && pr.videoDetails.title) || '';
      var tracks = (((pr.captions || {}).playerCaptionsTracklistRenderer || {}).captionTracks) || [];
      if (!tracks.length) return post({ error: 'NO_CAPTIONS', title: title });
      var en = tracks.filter(function (t) { return (t.languageCode || '').indexOf('en') === 0; });
      var track = en.filter(function (t) { return t.kind !== 'asr'; })[0] || en[0] || tracks[0];
      fetch(track.baseUrl + '&fmt=json3')
        .then(function (r) { return r.text(); })
        .then(function (txt) {
          if (!txt) return post({ error: 'EMPTY_TIMEDTEXT', title: title });
          var j = JSON.parse(txt);
          var segs = [];
          (j.events || []).forEach(function (ev) {
            if (!ev.segs || ev.aAppend === 1) return;
            var text = ev.segs.map(function (s) { return s.utf8 || ''; }).join('').replace(/\\s+/g, ' ').trim();
            if (!text) return;
            var startMs = ev.tStartMs || 0;
            segs.push({ startMs: startMs, endMs: startMs + (ev.dDurationMs || 0), text: text });
          });
          if (!segs.length) return post({ error: 'EMPTY_TIMEDTEXT', title: title });
          post({ title: title, segments: segs });
        })
        .catch(function (e) { post({ error: 'FETCH_FAILED:' + (e && e.message), title: title }); });
    } catch (e) { post({ error: 'INJECT_ERROR:' + (e && e.message) }); }
  }
  // ytInitialPlayerResponse is in the HTML, but give BotGuard a moment to run before fetching.
  var tries = 0;
  var iv = setInterval(function () {
    if (window.ytInitialPlayerResponse) { clearInterval(iv); setTimeout(grab, 1500); }
    else if (tries++ > 60) { clearInterval(iv); post({ error: 'NO_PLAYER_RESPONSE' }); }
  }, 200);
})();
true;
`;

/**
 * Imperative transcript fetcher backed by a hidden WebView.
 * Returns the element to render (somewhere always-mounted) plus a fetch(id) => Promise.
 */
export function useYoutubeTranscriptFetcher() {
  const [videoId, setVideoId] = useState<string | null>(null);
  const resolver = useRef<{
    resolve: (r: WebViewTranscriptResult) => void;
    reject: (e: Error) => void;
    timer: ReturnType<typeof setTimeout>;
  } | null>(null);

  const settle = useCallback(() => {
    const r = resolver.current;
    resolver.current = null;
    setVideoId(null);
    if (r) clearTimeout(r.timer);
    return r;
  }, []);

  const fetchTranscript = useCallback(
    (urlOrId: string) =>
      new Promise<WebViewTranscriptResult>((resolve, reject) => {
        const id = extractYoutubeId(urlOrId);
        if (!id) return reject(new Error('INVALID_YOUTUBE_URL'));
        const timer = setTimeout(() => {
          const r = settle();
          r?.reject(new Error('TIMEOUT'));
        }, TIMEOUT_MS);
        resolver.current = { resolve, reject, timer };
        setVideoId(id);
      }),
    [settle],
  );

  const onMessage = useCallback(
    (e: WebViewMessageEvent) => {
      const r = settle();
      if (!r) return;
      try {
        const data = JSON.parse(e.nativeEvent.data) as
          | WebViewTranscriptResult
          | { error: string };
        if ('error' in data) r.reject(new Error(data.error));
        else r.resolve(data);
      } catch {
        r.reject(new Error('PARSE_ERROR'));
      }
    },
    [settle],
  );

  const transcriptWebView = videoId ? (
    <WebView
      key={videoId}
      source={{ uri: `https://www.youtube.com/watch?v=${videoId}` }}
      injectedJavaScript={INJECTED}
      onMessage={onMessage}
      // A desktop UA forces the full watch page (with ytInitialPlayerResponse + BotGuard),
      // not the stripped m.youtube.com layout.
      userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
      javaScriptEnabled
      domStorageEnabled
      thirdPartyCookiesEnabled
      // Hidden + non-interactive.
      style={{ width: 1, height: 1, position: 'absolute', top: -1000, opacity: 0 }}
      pointerEvents="none"
    />
  ) : null;

  return { transcriptWebView, fetchTranscript };
}
